import type { AnnuaireEntry } from "./annuaire-map-canvas";

export const INITIAL_ANNUAIRE_ENTRIES: AnnuaireEntry[] = [
  {
    id: "asso-1",
    name: "Pik Pik Environnement",
    legalIdentity: "Association Pik Pik Environnement (SIREN 803 350 367)",
    kind: "association",
    types: ["environnemental", "social"],
    description:
      "Accompagne les Francilien·ne·s dans la transition écologique avec des ateliers terrain.",
    location: "Issy-les-Moulineaux",
    lat: 48.825,
    lng: 2.27,
    websiteUrl: "https://www.pikpik.org/",
    instagramUrl: "https://www.instagram.com/pikpik_environnement/",
    coveredArrondissements: [15, 16],
    contributionTypes: ["materiel", "communication"],
    availability: "Lundi au samedi, 10h-18h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/pikpik_environnement/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-12",
    recentActivityAt: "2026-04-10",
    internalAdminContact: {
      referentName: "Kamera Vesic",
      email: "contact@pikpik.org",
      phone: "01 41 46 05 00",
    },
  },
  {
    id: "asso-2",
    name: "Le Carillon / La Cloche",
    legalIdentity: "Association La Cloche (RNA W751221768)",
    kind: "association",
    types: ["social", "humanitaire"],
    description:
      "Réseau solidaire de commerçant·e·s engagé·e·s pour aider les personnes sans domicile.",
    location: "Paris Centre",
    lat: 48.86,
    lng: 2.35,
    websiteUrl: "https://lacloche.org/le-carillon",
    instagramUrl: "https://www.instagram.com/assolacloche/",
    coveredArrondissements: [1, 2, 3, 4, 10, 11],
    contributionTypes: ["accueil", "logistique", "communication"],
    availability: "Tous les jours, 9h-20h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/assolacloche/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-13",
    recentActivityAt: "2026-04-11",
    internalAdminContact: {
      referentName: "Valerie Fayard",
      email: "valerie.fayard@lacloche.org",
      phone: "Non publié",
    },
  },
  {
    id: "com-1",
    name: "La Textilerie",
    legalIdentity: "SAS La Textilerie (SIREN 824 531 417)",
    kind: "commerce",
    types: ["environnemental", "social"],
    description:
      "Tiers-lieu mode responsable : friperie, couture, ateliers de sensibilisation.",
    location: "Paris 10e",
    lat: 48.875,
    lng: 2.36,
    websiteUrl: "https://latextilerie.fr/",
    instagramUrl: "https://www.instagram.com/latextilerieparis/",
    coveredArrondissements: [9, 10, 11],
    contributionTypes: ["accueil", "materiel", "communication"],
    availability: "Mardi au dimanche, 11h-19h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/latextilerieparis/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-15",
    recentActivityAt: "2026-04-14",
    internalAdminContact: {
      referentName: "Elsa Monsegur",
      email: "contact@latextilerie.fr",
      phone: "01 40 35 77 14",
    },
  },
  {
    id: "asso-3",
    name: "Carton Plein",
    legalIdentity: "Association Carton Plein (RNA W751216999)",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Inclusion sociale et réemploi via déménagements à vélo et logistique locale.",
    location: "Paris 11e / 18e",
    lat: 48.89,
    lng: 2.355,
    websiteUrl: "https://www.cartonplein.org/",
    instagramUrl: "https://www.instagram.com/cartonplein_org/",
    coveredArrondissements: [11, 18, 19, 20],
    contributionTypes: ["logistique", "materiel", "accueil"],
    availability: "Sur demande + créneaux hebdomadaires",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.cartonplein.org/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-11",
    recentActivityAt: "2026-04-09",
    internalAdminContact: {
      referentName: "Equipe Carton Plein",
      email: "bonjour@cartonplein.org",
      phone: "01 44 85 37 01",
    },
  },
  {
    id: "asso-4",
    name: "Academie du Climat",
    legalIdentity: "Ville de Paris - Académie du Climat (équipement municipal)",
    kind: "association",
    types: ["environnemental", "social"],
    description:
      "Lieu d'engagement climat ouvert au public: ateliers, débats, formations, programmation régulière et réseau citoyen.",
    location: "Paris 4e",
    lat: 48.8569,
    lng: 2.3564,
    websiteUrl: "https://www.academieduclimat.paris/",
    instagramUrl: "https://www.instagram.com/academieduclimat/",
    coveredArrondissements: [1, 2, 3, 4, 11, 12],
    contributionTypes: ["accueil", "logistique", "communication"],
    availability: "Lundi au samedi, 9h-fin de soiree, agenda ateliers mis à jour régulièrement",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.academieduclimat.paris/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-17",
    recentActivityAt: "2026-04-16",
    internalAdminContact: {
      referentName: "Mariane Lavallee",
      email: "mariane.lavallee@paris.fr",
      phone: "01 71 28 13 66",
    },
  },
  {
    id: "collectif-1",
    name: "Cercle de parole - Eco-anxiété",
    legalIdentity: "Collectif eco-anxiété Paris (déclaration en cours)",
    kind: "groupe_parole",
    types: ["social", "environnemental"],
    description:
      "Collectif itinérant pour échanger sur les émotions liées à la crise climatique.",
    location: "Paris itinérant",
    lat: 48.865,
    lng: 2.34,
    coveredArrondissements: [5, 6, 11, 12, 13],
    contributionTypes: ["accueil", "communication"],
    availability: "1 fois par semaine, en soirée",
    verificationStatus: "en_cours",
    qualificationStatus: "contact_non_qualifie",
    lastUpdatedAt: "2026-03-02",
    recentActivityAt: "2026-02-20",
  },
  {
    id: "com-2",
    name: "La Collecterie Paris",
    legalIdentity: "Association La Collecterie (RNA W931014584)",
    kind: "commerce",
    types: ["environnemental", "social"],
    description:
      "Ressourcerie locale avec ateliers de réemploi et collecte de matériel.",
    location: "Montreuil",
    lat: 48.86,
    lng: 2.43,
    websiteUrl: "https://lacollecterie.org/",
    instagramUrl: "https://www.instagram.com/lacollecterie/",
    coveredArrondissements: [19, 20],
    contributionTypes: ["materiel", "logistique", "financement"],
    availability: "Mercredi au dimanche, 10h-18h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/lacollecterie/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-08",
    recentActivityAt: "2026-04-05",
  },
  {
    id: "com-3",
    name: "Klin d'oeil",
    legalIdentity: "Klin d'oeil, boutique de createurs et ateliers artistiques (Bas Belleville, rue Deguerry, Paris 11e)",
    kind: "commerce",
    types: ["social"],
    description:
      "Boutique de createurs et lieu d'activites artistiques implante a Bas Belleville, au croisement des 11e, 19e et 20e arrondissements, avec une carte des bonnes adresses pour valoriser le quartier.",
    location: "Bas Belleville, rue Deguerry, Paris 11e",
    lat: 48.8667,
    lng: 2.3788,
    websiteUrl: "https://klindoeil.com",
    coveredArrondissements: [11, 19, 20],
    contributionTypes: ["accueil", "communication"],
    availability: "Selon programmation des ateliers et temps boutique",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://klindoeil.com",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-23",
    recentActivityAt: "2026-04-22",
  },
  {
    id: "du-1",
    name: "Diplôme Universitaire Engagement",
    legalIdentity: "Sorbonne Université - Diplôme Universitaire Engagement",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Formation de Sorbonne Université pour les acteurs engagés, étudiantes, professionnels et acteurs associatifs. Ce DU a permis d'initier le site web CleanMyMap en structurant le projet et le lien entre mobilisation citoyenne et territoires.",
    location: "Paris 5e",
    lat: 48.8489,
    lng: 2.3431,
    websiteUrl: "https://www.sorbonne-universite.fr/formation/",
    coveredArrondissements: [5],
    contributionTypes: ["communication", "accueil"],
    availability: "Semaines universitaires, 9h-18h. Dossier et inscriptions à consulter en ligne selon sessions annuelles.",
    primaryChannel: {
      platform: "site web",
      label: "Page Sorbonne Université",
      url: "https://www.sorbonne-universite.fr/formation/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-24",
    recentActivityAt: "2026-04-24",
  },
  {
    id: "evt-1",
    name: "La REcyclerie - Ateliers",
    legalIdentity: "SAS Sinny&Ooko - site La REcyclerie (SIREN 801 782 744)",
    kind: "evenement",
    types: ["environnemental"],
    description:
      "Programmation ateliers, réparation, potager urbain et événements citoyens.",
    location: "Paris 18e",
    lat: 48.896,
    lng: 2.344,
    websiteUrl: "https://www.larecyclerie.com/",
    instagramUrl: "https://www.instagram.com/larecyclerie/",
    coveredArrondissements: [17, 18],
    contributionTypes: ["accueil", "communication", "materiel"],
    availability: "Tous les week-ends + calendrier mensuel",
    primaryChannel: {
      platform: "site web",
      label: "Agenda site web",
      url: "https://www.larecyclerie.com/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-10",
    recentActivityAt: "2026-04-07",
  },
  {
    id: "ent-1",
    name: "Green Flex",
    legalIdentity: "Green Flex SAS (SIREN 912 540 881)",
    kind: "entreprise",
    types: ["environnemental"],
    description:
      "Accompagne les entreprises pour financer et opérer des actions locales.",
    location: "Paris 9e",
    lat: 48.874,
    lng: 2.333,
    coveredArrondissements: [8, 9, 10],
    contributionTypes: ["financement", "logistique", "communication"],
    availability: "Du lundi au vendredi, 9h-18h",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.greenflex.com/",
    },
    verificationStatus: "a_revalider",
    qualificationStatus: "contact_non_qualifie",
    lastUpdatedAt: "2026-04-23",
    recentActivityAt: "2026-04-22",
  },
];
