-- Create xp_audit table to log XP attributions
CREATE TABLE IF NOT EXISTS public.xp_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id text not null,
  actor_id text null, -- who triggered it (service or admin or user)
  reason text not null,
  xp_change integer not null,
  source_table text null,
  source_id text null,
  metadata jsonb not null default '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_xp_audit_user_created ON public.xp_audit(user_id, created_at desc);
CREATE INDEX IF NOT EXISTS idx_xp_audit_created_at ON public.xp_audit(created_at desc);

-- Unique constraint to avoid duplicated audits for same source (user_id, source_table, source_id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE tablename = 'xp_audit' AND indexname = 'uq_xp_audit_user_source'
  ) THEN
    CREATE UNIQUE INDEX uq_xp_audit_user_source ON public.xp_audit (user_id, source_table, source_id);
  END IF;
END$$;

-- Helper view: total xp per user per day
CREATE MATERIALIZED VIEW IF NOT EXISTS public.xp_audit_daily AS
SELECT user_id, date_trunc('day', created_at)::date as day, sum(xp_change) as xp_total
FROM public.xp_audit
GROUP BY user_id, date_trunc('day', created_at)::date;
