-- Operational stores moved from local JSON files to Supabase tables.

create table if not exists public.admin_operations_audit (
  id bigint generated by default as identity primary key,
  operation_id text not null,
  at timestamptz not null default now(),
  actor_user_id text not null,
  operation_type text not null check (operation_type in ('moderation', 'import_dry_run', 'import_confirm')),
  outcome text not null check (outcome in ('success', 'error')),
  target_id text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists idx_admin_operations_audit_at_desc on public.admin_operations_audit(at desc);
create index if not exists idx_admin_operations_audit_operation_id on public.admin_operations_audit(operation_id);

create table if not exists public.funnel_events (
  id bigint generated by default as identity primary key,
  at timestamptz not null default now(),
  session_id text not null,
  user_id text,
  step text not null check (step in ('view_new', 'start_form', 'submit_success')),
  mode text not null check (mode in ('quick', 'complete')),
  meta jsonb not null default '{}'::jsonb
);

create index if not exists idx_funnel_events_at_desc on public.funnel_events(at desc);
create index if not exists idx_funnel_events_step_mode on public.funnel_events(step, mode);

create table if not exists public.checklist_progress (
  user_id text not null,
  checklist_id text not null,
  checks jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, checklist_id)
);

create index if not exists idx_checklist_progress_updated_at_desc on public.checklist_progress(updated_at desc);

create table if not exists public.runbook_checks (
  profile text primary key check (profile in ('ops', 'admin', 'dev')),
  status text not null check (status in ('pass', 'fail')),
  duration_seconds integer not null check (duration_seconds >= 1 and duration_seconds <= 3600),
  last_run_at timestamptz,
  notes jsonb not null default '[]'::jsonb
);

alter table public.admin_operations_audit enable row level security;
alter table public.funnel_events enable row level security;
alter table public.checklist_progress enable row level security;
alter table public.runbook_checks enable row level security;

drop policy if exists admin_operations_audit_service_only on public.admin_operations_audit;
create policy admin_operations_audit_service_only on public.admin_operations_audit
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists funnel_events_service_only on public.funnel_events;
create policy funnel_events_service_only on public.funnel_events
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists checklist_progress_service_only on public.checklist_progress;
create policy checklist_progress_service_only on public.checklist_progress
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists runbook_checks_service_only on public.runbook_checks;
create policy runbook_checks_service_only on public.runbook_checks
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
