-- 20260521000011_governance_monthly_reports.sql

create table if not exists public.governance_monthly_reports (
  id bigint generated by default as identity primary key,
  report_key text not null,
  report_month date not null,
  generated_at timestamptz not null default now(),
  version text not null,
  title text not null,
  payload jsonb not null default '{}'::jsonb
);

create unique index if not exists uq_governance_monthly_reports_key_month
  on public.governance_monthly_reports(report_key, report_month);

create index if not exists idx_governance_monthly_reports_generated_at_desc
  on public.governance_monthly_reports(generated_at desc);

alter table public.governance_monthly_reports enable row level security;

drop policy if exists governance_monthly_reports_service_only on public.governance_monthly_reports;
create policy governance_monthly_reports_service_only on public.governance_monthly_reports
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
