-- Discussion API rate limits
-- Rules:
-- - cooldown: max 1 message every 30 seconds per user
-- - daily cap: max 10 messages per day per user (Europe/Paris day boundary)

create table if not exists public.community_message_quota_daily (
  user_id text not null,
  occurred_on date not null,
  message_count integer not null default 0 check (message_count >= 0),
  last_message_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, occurred_on)
);

create table if not exists public.community_message_quota_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id text not null,
  channel text not null check (channel in ('discussion_event', 'bug_report')),
  occurred_on date not null
);

create index if not exists idx_community_message_quota_events_user_created_desc
  on public.community_message_quota_events(user_id, created_at desc);

alter table public.community_message_quota_daily enable row level security;
alter table public.community_message_quota_events enable row level security;

drop policy if exists community_message_quota_daily_service_only
  on public.community_message_quota_daily;
create policy community_message_quota_daily_service_only
  on public.community_message_quota_daily
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists community_message_quota_events_service_only
  on public.community_message_quota_events;
create policy community_message_quota_events_service_only
  on public.community_message_quota_events
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create or replace function public.reserve_community_message_slot(
  p_user_id text,
  p_channel text
)
returns table (
  allowed boolean,
  reason text,
  retry_after_seconds integer,
  messages_today integer,
  remaining_today integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_day date := (now() at time zone 'Europe/Paris')::date;
  v_quota_row public.community_message_quota_daily%rowtype;
  v_retry_seconds integer := 0;
  v_daily_limit integer := 10;
  v_cooldown_seconds integer := 30;
begin
  if p_user_id is null or length(trim(p_user_id)) = 0 then
    raise exception 'p_user_id is required';
  end if;

  if p_channel not in ('discussion_event', 'bug_report') then
    raise exception 'Invalid p_channel: %', p_channel;
  end if;

  insert into public.community_message_quota_daily (
    user_id,
    occurred_on,
    message_count,
    last_message_at,
    updated_at
  )
  values (p_user_id, v_day, 0, null, v_now)
  on conflict (user_id, occurred_on) do nothing;

  select *
  into v_quota_row
  from public.community_message_quota_daily
  where user_id = p_user_id
    and occurred_on = v_day
  for update;

  if v_quota_row.last_message_at is not null
    and v_now < (v_quota_row.last_message_at + make_interval(secs => v_cooldown_seconds))
  then
    v_retry_seconds := ceil(
      extract(
        epoch
        from ((v_quota_row.last_message_at + make_interval(secs => v_cooldown_seconds)) - v_now)
      )
    )::integer;

    return query
    select
      false,
      'cooldown',
      greatest(v_retry_seconds, 1),
      v_quota_row.message_count,
      greatest(v_daily_limit - v_quota_row.message_count, 0);
    return;
  end if;

  if v_quota_row.message_count >= v_daily_limit then
    return query
    select
      false,
      'daily_limit',
      null::integer,
      v_quota_row.message_count,
      0;
    return;
  end if;

  update public.community_message_quota_daily
  set
    message_count = message_count + 1,
    last_message_at = v_now,
    updated_at = v_now
  where user_id = p_user_id
    and occurred_on = v_day
  returning *
  into v_quota_row;

  insert into public.community_message_quota_events (
    user_id,
    channel,
    occurred_on
  )
  values (
    p_user_id,
    p_channel,
    v_day
  );

  return query
  select
    true,
    'ok',
    0,
    v_quota_row.message_count,
    greatest(v_daily_limit - v_quota_row.message_count, 0);
end;
$$;

revoke all on function public.reserve_community_message_slot(text, text) from public;
grant execute on function public.reserve_community_message_slot(text, text) to service_role;
