-- Gamification progression durable (XP, niveaux, badges)

create table if not exists public.progression_profiles (
  user_id text primary key,
  xp_total integer not null default 0,
  xp_validated integer not null default 0,
  xp_pending integer not null default 0,
  current_level integer not null default 1,
  potential_level integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.progression_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id text not null,
  event_type text not null,
  source_table text not null,
  source_id text not null,
  status_phase text not null check (status_phase in ('pending', 'validated', 'rejected')),
  weight integer not null check (weight between 1 and 5),
  xp_base integer not null check (xp_base >= 0),
  xp_awarded integer not null check (xp_awarded >= 0),
  occurred_on date not null,
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists uq_progression_events_daily_by_type
  on public.progression_events(user_id, event_type, occurred_on);

create unique index if not exists uq_progression_events_source_phase
  on public.progression_events(event_type, source_id, status_phase);

create index if not exists idx_progression_events_user_created_desc
  on public.progression_events(user_id, created_at desc);

create index if not exists idx_progression_events_user_type
  on public.progression_events(user_id, event_type);

alter table public.progression_profiles enable row level security;
alter table public.progression_events enable row level security;

drop policy if exists progression_profiles_service_only on public.progression_profiles;
create policy progression_profiles_service_only on public.progression_profiles
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists progression_events_service_only on public.progression_events;
create policy progression_events_service_only on public.progression_events
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
