-- 20260627000004_public_surface_snapshots.sql

create table if not exists public.public_surface_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_key text not null,
  snapshot_date date not null,
  generated_at timestamptz not null default now(),
  version text not null,
  title text not null,
  payload jsonb not null default '{}'::jsonb,
  meta jsonb not null default '{}'::jsonb
);

create unique index if not exists uq_public_surface_snapshots_key_date
  on public.public_surface_snapshots(snapshot_key, snapshot_date);

create index if not exists idx_public_surface_snapshots_generated_at_desc
  on public.public_surface_snapshots(generated_at desc);

create index if not exists idx_public_surface_snapshots_key_generated_at_desc
  on public.public_surface_snapshots(snapshot_key, generated_at desc);

alter table public.public_surface_snapshots enable row level security;

drop policy if exists public_surface_snapshots_service_only on public.public_surface_snapshots;
create policy public_surface_snapshots_service_only on public.public_surface_snapshots
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
