import type { AnnuaireEntry } from "../annuaire-map-canvas";

export const EVENEMENTS_ENTRIES: AnnuaireEntry[] = [
  {
    id: "evt-1",
    name: "La REcyclerie - Ateliers",
    legalIdentity: "SAS Sinny&Ooko - site La REcyclerie (SIREN 801 782 744)",
    kind: "evenement",
    types: ["environnemental"],
    description:
      "Programmation ateliers, réparation, potager urbain et événements citoyens.",
    location: "Paris 18e",
    lat: 48.896,
    lng: 2.344,
    websiteUrl: "https://www.larecyclerie.com/",
    instagramUrl: "https://www.instagram.com/larecyclerie/",
    coveredArrondissements: [17, 18],
    contributionTypes: ["accueil", "communication", "materiel"],
    availability: "Tous les week-ends + calendrier mensuel",
    primaryChannel: {
      platform: "site web",
      label: "Agenda site web",
      url: "https://www.larecyclerie.com/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-10",
    recentActivityAt: "2026-04-07",
  },
  {
    id: "evt-paris-nettoyages",
    name: "Paris.fr - Nettoyages participatifs",
    legalIdentity: "Ville de Paris - Direction de la Propreté et du Plateau",
    kind: "evenement",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Plateforme officielle de la Ville de Paris pour organiser et rejoindre des nettoyages participatifs. Aucune autorisation requise.",
    description: "Source officielle pour organiser un nettoyage à Paris. La Ville indique qu'il n'y a pas besoin d'autorisation spécifique pour ce type d'événement. Inscrivez-vous pour nettoyer les rues, parks et canaux de Paris.",
    location: "Paris",
    lat: 48.8566,
    lng: 2.3522,
    websiteUrl: "https://www.paris.fr/Nettoyages-participatifs",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["logistique", "materiel", "communication"],
    tags: ["Nettoyage", "Official", "Paris", "Participation citoyenne"],
    availability: "Événements réguliers toute l'année",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "evt-j-agis-nature",
    name: "J'agis pour la nature",
    legalIdentity: "Université Paris Cité / Structures partenaires",
    kind: "evenement",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Plateforme pour organiser et rejoindre des événements de bénévolat nature en France, notamment à Paris.",
    description: "Plateforme citoyenne pour l'action environnementale. Permet de créer et rejoindre des événements de bénévolat : nettoyages, plantations, atlas de la biodiversité urbaine, etc. Filtre disponible pour Paris et la région.",
    location: "France / Paris",
    lat: 48.8566,
    lng: 2.3522,
    websiteUrl: "https://jagispourlanature.fr",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["materiel", "logistique", "communication"],
    tags: ["Bénévolat", "Nature", "France", "Événements"],
    availability: "Tout au long de l'année",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "evt-je-veux-aider",
    name: "JeVeuxAider",
    legalIdentity: "La Croix-Rouge Française",
    kind: "evenement",
    types: ["social", "humanitaire", "environnemental"],
    isFeatured: true,
    featuredReason: "Plateforme nationale pour rejoindre des missions de bénévolat, avec filtre Paris et événements environnementaux.",
    description: "Plateforme de la Croix-Rouge française pour trouver et s'inscrire à des missions de bénévolat près de chez soi. Disponible à Paris avec des missions variées : environnement, aide alimentaire, accompagnement, etc.",
    location: "France / Paris",
    lat: 48.8566,
    lng: 2.3522,
    websiteUrl: "https://www.jeveuxaider.gouv.fr",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["logistique", "accueil", "communication"],
    tags: ["Bénévolat", "National", "Multi-thématiques", "France"],
    availability: "Missions toute l'année",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
];
