import type { AnnuaireEntrySeedInput } from "@/lib/partners/annuaire-types";

export const EVENEMENTS_ENTRIES: AnnuaireEntrySeedInput[] = [
  {
    id: "evt-1",
    name: "La REcyclerie - Ateliers",
    legalIdentity: "SAS Sinny&Ooko - site La REcyclerie (SIREN 801 782 744)",
    kind: "evenement",
    types: ["environnemental"],
    description:
      "Programmation ateliers, réparation, potager urbain et événements citoyens.",
    location: "Paris 18e",
    lat: 48.896,
    lng: 2.344,
    websiteUrl: "https://www.larecyclerie.com/",
    instagramUrl: "https://www.instagram.com/larecyclerie/",
    coveredArrondissements: [17, 18],
    contributionTypes: ["accueil", "communication", "materiel"],
    primaryChannel: {
      platform: "site web",
      label: "Agenda site web",
      url: "https://www.larecyclerie.com/",
    },
  },
  {
    id: "evt-paris-nettoyages",
    name: "Paris.fr - Nettoyages participatifs",
    legalIdentity: "Ville de Paris — Direction de la Propreté et de l’Eau",
    kind: "evenement",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Page de la Ville pour organiser un nettoyage participatif à Paris.",
    description: "Page de la Ville de Paris permettant d’organiser un nettoyage participatif et de faciliter la coordination avec les services de propreté.",
    location: "Paris",
    lat: 48.8566,
    lng: 2.3522,
    websiteUrl: "https://www.paris.fr/Nettoyages-participatifs",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["logistique", "materiel", "communication"],
    tags: ["Nettoyage", "Paris", "Participation citoyenne"],
  },
  {
    id: "evt-j-agis-nature",
    name: "J'agis pour la nature",
    legalIdentity: "Fondation pour la Nature et l’Homme — projet J’agis pour la nature",
    kind: "evenement",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Plateforme pour organiser et rejoindre des événements de bénévolat nature en France, notamment à Paris.",
    description: "Plateforme gratuite dédiée au bénévolat nature et à la mise en relation avec les structures organisatrices.",
    location: "France / Paris",
    lat: 48.8566,
    lng: 2.3522,
    websiteUrl: "https://www.jagispourlanature.org/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["materiel", "logistique", "communication"],
    tags: ["Bénévolat", "Nature", "France", "Événements"],
  },
  {
    id: "evt-je-veux-aider",
    name: "JeVeuxAider",
    legalIdentity: "Réserve Civique — JeVeuxAider.gouv.fr",
    kind: "evenement",
    types: ["social", "humanitaire", "environnemental"],
    isFeatured: true,
    featuredReason: "Plateforme nationale pour rejoindre des missions de bénévolat, avec filtre Paris et événements environnementaux.",
    description: "Plateforme publique du bénévolat permettant de trouver des missions proposées par associations, collectivités et organismes publics.",
    location: "France / Paris",
    lat: 48.8566,
    lng: 2.3522,
    websiteUrl: "https://www.jeveuxaider.gouv.fr",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["logistique", "accueil", "communication"],
    tags: ["Bénévolat", "National", "Multi-thématiques", "France"],
  },
];
