import type { AnnuaireEntrySeedInput } from "@/lib/partners/annuaire-types";

export const ENTREPRISES_ENTRIES: AnnuaireEntrySeedInput[] = [
  {
    id: "com-1",
    name: "La Textilerie",
    legalIdentity: "SAS La Textilerie (SIREN 824 531 417)",
    kind: "commerce",
    types: ["environnemental", "social"],
    description:
      "Tiers-lieu mode responsable : friperie, couture, ateliers de sensibilisation.",
    location: "Paris 10e",
    lat: 48.875,
    lng: 2.36,
    websiteUrl: "https://latextilerie.fr/",
    instagramUrl: "https://www.instagram.com/latextilerieparis/",
    coveredArrondissements: [9, 10, 11],
    contributionTypes: ["accueil", "materiel", "communication"],
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/latextilerieparis/",
    },
    internalAdminContact: {
      referentName: "Elsa Monsegur",
      email: "contact@latextilerie.fr",
      phone: "01 40 35 77 14",
    },
  },
  {
    id: "asso-megots-alcome",
    name: "ALCOME",
    legalIdentity: "Éco-organisme ALCOME",
    kind: "entreprise",
    scope: "national",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Éco-organisme de la filière REP des produits du tabac.",
    description: "Éco-organisme agréé de la filière REP des produits du tabac, engagé dans la réduction des mégots dans l'espace public.",
    location: "France",
    lat: 48.87,
    lng: 2.32,
    websiteUrl: "https://www.alcome.eco",
    coveredArrondissements: [],
    contributionTypes: ["financement", "materiel", "communication"],
    tags: ["Mégots", "Eco-organisme", "Collectivités", "Sensibilisation"],
  },
  {
    id: "asso-megots-ecomegot",
    name: "Écomégot",
    legalIdentity: "Écomégot SAS (Économie circulaire)",
    kind: "entreprise",
    types: ["environnemental"],
    description: "Service de collecte et recyclage de mégots spécialisé pour les événements et cleanups spécialisés. Orientation utile pour les collectes ciblées.",
    location: "France / Paris",
    lat: 48.85,
    lng: 2.35,
    websiteUrl: "https://www.ecomegot.com",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "Recyclage", "Événements", "Collecte spécialisée"],
  },
  {
    id: "asso-megots-cyclope",
    name: "Cy-Clope",
    legalIdentity: "Cy-Clope SAS",
    kind: "entreprise",
    types: ["environnemental"],
    description: "Solution de gestion des zones fumeurs, de collecte et de valorisation des mégots pour les entreprises et les lieux publics.",
    location: "Saint-Ouen / Paris",
    lat: 48.91,
    lng: 2.33,
    websiteUrl: "https://www.cy-clope.fr",
    coveredArrondissements: [],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "Entreprise", "Cendriers connectés", "Propreté urbaine"],
  },
  {
    id: "asso-megots-tchaomegot",
    name: "TchaoMegot",
    legalIdentity: "Tchao Megot SAS (Économie Circulaire)",
    kind: "entreprise",
    types: ["environnemental"],
    description: "Collecte, dépollution et recyclage de mégots, avec un procédé breveté sans eau ni solvant toxique.",
    location: "National / Paris",
    lat: 48.85,
    lng: 2.33,
    websiteUrl: "https://tchaomegot.com",
    coveredArrondissements: [],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "B2B", "Collectivités", "Innovation"],
  },
  {
    id: "com-2",
    name: "La Collecterie Paris",
    legalIdentity: "Association La Collecterie (RNA W931014584)",
    kind: "commerce",
    types: ["environnemental", "social"],
    description:
      "Ressourcerie locale avec ateliers de réemploi et collecte de matériel.",
    location: "Montreuil",
    lat: 48.86,
    lng: 2.43,
    websiteUrl: "https://lacollecterie.org/",
    instagramUrl: "https://www.instagram.com/lacollecterie/",
    coveredArrondissements: [19, 20],
    contributionTypes: ["materiel", "logistique", "financement"],
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/lacollecterie/",
    },
  },
  {
    id: "com-3",
    name: "Klin d'oeil",
    legalIdentity: "Klin d'oeil, boutique de createurs et ateliers artistiques (Bas Belleville, rue Deguerry, Paris 11e)",
    kind: "commerce",
    types: ["social"],
    description:
      "Boutique de createurs et lieu d'activites artistiques implante a Bas Belleville, au croisement des 11e, 19e et 20e arrondissements, avec une carte des bonnes adresses pour valoriser le quartier.",
    location: "Bas Belleville, rue Deguerry, Paris 11e",
    lat: 48.8667,
    lng: 2.3788,
    websiteUrl: "https://klindoeil.com",
    coveredArrondissements: [11, 19, 20],
    contributionTypes: ["accueil", "communication"],
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://klindoeil.com",
    },
  },
  {
    id: "ent-1",
    name: "Green Flex",
    legalIdentity: "Green Flex SAS (SIREN 912 540 881)",
    kind: "entreprise",
    types: ["environnemental"],
    description:
      "Accompagne les entreprises pour financer et opérer des actions locales.",
    location: "Paris 9e",
    lat: 48.874,
    lng: 2.333,
    coveredArrondissements: [8, 9, 10],
    contributionTypes: ["financement", "logistique", "communication"],
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.greenflex.com/",
    },
  },
];
