import type { AnnuaireEntry } from "../annuaire-map-canvas";

const ASSOCIATION_PROFILES: Record<string, AnnuaireEntry["associationProfile"]> = {
  "asso-1": {
    mission: "Accompagner les Francilien·ne·s dans la transition écologique avec des ateliers terrain et des relais de quartier.",
    recurringNeeds: ["Matériel", "Relais de communication", "Bénévoles logistiques"],
    pastActions: [
      "Ateliers de sensibilisation et de transition écologique",
      "Mobilisations de quartier autour de la réduction des déchets",
      "Relais terrain avec partenaires locaux",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 18,
      zonesCovered: 2,
      recurrence: "Ateliers réguliers",
      lastActionAt: "2026-04-10",
      note: "Ateliers et relais de terrain documentés sur les 15e et 16e arrondissements.",
    },
    structureStatus: "validated",
  },
  "asso-2": {
    mission: "Réseau solidaire de proximité pour soutenir les personnes sans domicile et animer les commerces partenaires.",
    recurringNeeds: ["Bénévoles d'accueil", "Bénévoles logistiques", "Relais de communication"],
    pastActions: [
      "Animation du réseau de commerçant·e·s solidaires",
      "Relais d'aide et d'orientation de terrain",
      "Coordination de proximité dans Paris centre et l'Est parisien",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 42,
      zonesCovered: 6,
      recurrence: "Actions quotidiennes",
      lastActionAt: "2026-04-11",
      note: "Réseau actif avec de nombreux points de contact de quartier.",
    },
    structureStatus: "active_validated",
  },
  "asso-3": {
    mission: "Inclusion sociale et réemploi via des déménagements à vélo et une logistique locale utile.",
    recurringNeeds: ["Bénévoles logistiques", "Matériel", "Bénévoles d'accueil"],
    pastActions: [
      "Déménagements à vélo et logistique circulaire",
      "Accompagnement d'équipes bénévoles sur le terrain",
      "Actions de réemploi et d'accueil local",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 24,
      zonesCovered: 4,
      recurrence: "Actions hebdomadaires",
      lastActionAt: "2026-04-09",
      note: "Activité régulière sur le 11e, le 18e, le 19e et le 20e.",
    },
    structureStatus: "validated",
  },
  "asso-4": {
    mission: "Lieu d'engagement climat ouvert au public, centré sur les ateliers, les débats et la programmation citoyenne.",
    recurringNeeds: ["Bénévoles d'accueil", "Bénévoles logistiques", "Relais de communication"],
    pastActions: [
      "Programmation régulière d'ateliers et de débats",
      "Accueil du public et animation de réseau citoyen",
      "Diffusion de ressources climat et quartier",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 60,
      zonesCovered: 6,
      recurrence: "Programmation régulière",
      lastActionAt: "2026-04-16",
      note: "Hub reconnu pour la mobilisation citoyenne et le climat.",
    },
    structureStatus: "active_validated",
  },
  "asso-featured-1": {
    mission: "Action terrain exemplaire sur la propreté urbaine, le recyclage et la mobilisation citoyenne dans le 19e.",
    recurringNeeds: ["Matériel", "Bénévoles logistiques", "Relais de communication"],
    pastActions: [
      "Collectes de déchets de quartier",
      "Opérations de propreté urbaine et de recyclage",
      "Mobilisations citoyennes récurrentes dans le 19e",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 31,
      zonesCovered: 1,
      recurrence: "Sorties hebdomadaires",
      lastActionAt: "2026-04-20",
      note: "Focus très local sur le 19e arrondissement.",
    },
    structureStatus: "active_validated",
  },
  "asso-featured-2": {
    mission: "Soutien aux plus démunis via des distributions alimentaires et un accompagnement social sans conditions.",
    recurringNeeds: ["Bénévoles d'accueil", "Bénévoles logistiques", "Dons"],
    pastActions: [
      "Distributions alimentaires de proximité",
      "Accompagnement social sans conditions",
      "Animation d'un réseau d'entraide local",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 54,
      zonesCovered: 1,
      recurrence: "Actions quotidiennes",
      lastActionAt: "2026-04-22",
      note: "Historique concentré sur le 15e et les besoins de proximité.",
    },
    structureStatus: "active_validated",
  },
  "asso-featured-6": {
    mission: "Protection des océans, du littoral et de la biodiversité marine avec un appui aux relais locaux.",
    recurringNeeds: ["Dons", "Relais de communication", "Matériel"],
    pastActions: [
      "Soutien à des projets de protection du littoral",
      "Relais de campagnes de sensibilisation",
      "Mobilisation de projets locaux sur la biodiversité marine",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 38,
      zonesCovered: 1,
      recurrence: "Campagnes régulières",
      lastActionAt: "2026-04-10",
      note: "Action surtout nationale avec appuis locaux ponctuels.",
    },
    structureStatus: "validated",
  },
  "asso-zd-greenminded": {
    mission: "Sensibilisation zéro-déchet, zéro-mégot et pollution plastique avec ateliers et interventions scolaires.",
    recurringNeeds: ["Relais de communication", "Bénévoles d'accueil", "Matériel"],
    pastActions: [
      "Ateliers zéro-déchet et sensibilisation grand public",
      "Interventions scolaires et pédagogiques",
      "Mobilisations zéro-mégot et lutte plastique",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 29,
      zonesCovered: 12,
      recurrence: "Interventions régulières",
      lastActionAt: "2026-05-01",
      note: "Réseau très mobilisé sur plusieurs arrondissements parisiens.",
    },
    structureStatus: "active_validated",
  },
  "asso-gestes-propres": {
    mission: "Association nationale dédiée à la sensibilisation, aux relais de terrain et à l'appui des collectifs locaux partout en France.",
    recurringNeeds: ["Relais de communication", "Bénévoles logistiques", "Matériel"],
    pastActions: [
      "Mobilisation d'antennes locales",
      "Campagnes nationales de sensibilisation",
      "Appui aux collectifs terrain",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 120,
      zonesCovered: 20,
      recurrence: "Réseau national continu",
      lastActionAt: "2026-05-01",
      note: "Structure nationale utile pour la diffusion et l'essaimage local.",
    },
    structureStatus: "validated",
  },
  "du-1": {
    mission: "Formation des acteurs engagés et structuration du lien entre mobilisation citoyenne et territoires.",
    recurringNeeds: ["Relais de communication", "Bénévoles d'accueil"],
    pastActions: [
      "Formation d'étudiant·e·s et d'acteurs engagés",
      "Structuration de projets d'engagement local",
      "Transmission de méthodes et de cadres de travail",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 12,
      zonesCovered: 1,
      recurrence: "Sessions universitaires",
      lastActionAt: "2026-04-24",
      note: "Impact surtout pédagogique et structurant.",
    },
    structureStatus: "validated",
  },
  "asso-surfrider-paris": {
    mission: "Protection de l'océan et du littoral, avec des collectes urbaines et des initiatives océanes locales.",
    recurringNeeds: ["Matériel", "Bénévoles logistiques", "Relais de communication"],
    pastActions: [
      "Collectes de déchets sur les berges de Seine",
      "Initiatives Océanes urbaines",
      "Mobilisations locales de protection du littoral",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 46,
      zonesCovered: 16,
      recurrence: "Collectes régulières",
      lastActionAt: "2026-05-01",
      note: "Fort maillage parisien pour des actions environnementales récurrentes.",
    },
    structureStatus: "active_validated",
  },
  "asso-zerowaste-paris": {
    mission: "Groupe local militant pour la réduction des déchets à la source, la sensibilisation et le plaidoyer zero waste.",
    recurringNeeds: ["Relais de communication", "Bénévoles d'accueil", "Matériel"],
    pastActions: [
      "Ateliers zéro déchet et sensibilisation",
      "Plaidoyer local pour la réduction à la source",
      "Actions terrain pour le zéro déchet dans la capitale",
    ],
    usefulResources: [],
    publicCalls: [],
    impactHistory: {
      actionCount: 52,
      zonesCovered: 20,
      recurrence: "Ateliers mensuels",
      lastActionAt: "2026-05-01",
      note: "Couverture parisienne très large et cadence régulière.",
    },
    structureStatus: "active_validated",
  },
};

const ASSOCIATIONS_BASE_ENTRIES: AnnuaireEntry[] = [
  {
    id: "asso-1",
    name: "Pik Pik Environnement",
    legalIdentity: "Association Pik Pik Environnement (SIREN 803 350 367)",
    kind: "association",
    types: ["environnemental", "social"],
    description:
      "Accompagne les Francilien·ne·s dans la transition écologique avec des ateliers terrain.",
    location: "Issy-les-Moulineaux",
    lat: 48.825,
    lng: 2.27,
    websiteUrl: "https://www.pikpik.org/",
    instagramUrl: "https://www.instagram.com/pikpik_environnement/",
    coveredArrondissements: [15, 16],
    contributionTypes: ["materiel", "communication"],
    availability: "Lundi au samedi, 10h-18h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/pikpik_environnement/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-12",
    recentActivityAt: "2026-04-10",
    internalAdminContact: {
      referentName: "Kamera Vesic",
      email: "contact@pikpik.org",
      phone: "01 41 46 05 00",
    },
  },
  {
    id: "asso-2",
    name: "Le Carillon / La Cloche",
    legalIdentity: "Association La Cloche (RNA W751221768)",
    kind: "association",
    types: ["social", "humanitaire"],
    description:
      "Réseau solidaire de commerçant·e·s engagé·e·s pour aider les personnes sans domicile.",
    location: "Paris Centre",
    lat: 48.86,
    lng: 2.35,
    websiteUrl: "https://lacloche.org/le-carillon",
    instagramUrl: "https://www.instagram.com/assolacloche/",
    coveredArrondissements: [1, 2, 3, 4, 10, 11],
    contributionTypes: ["accueil", "logistique", "communication"],
    availability: "Tous les jours, 9h-20h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/assolacloche/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-13",
    recentActivityAt: "2026-04-11",
    internalAdminContact: {
      referentName: "Valerie Fayard",
      email: "valerie.fayard@lacloche.org",
      phone: "Non publié",
    },
  },
  {
    id: "asso-3",
    name: "Carton Plein",
    legalIdentity: "Association Carton Plein (RNA W751216999)",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Inclusion sociale et réemploi via déménagements à vélo et logistique locale.",
    location: "Paris 11e / 18e",
    lat: 48.89,
    lng: 2.355,
    websiteUrl: "https://www.cartonplein.org/",
    instagramUrl: "https://www.instagram.com/cartonplein_org/",
    coveredArrondissements: [11, 18, 19, 20],
    contributionTypes: ["logistique", "materiel", "accueil"],
    availability: "Sur demande + créneaux hebdomadaires",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.cartonplein.org/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-11",
    recentActivityAt: "2026-04-09",
    internalAdminContact: {
      referentName: "Equipe Carton Plein",
      email: "bonjour@cartonplein.org",
      phone: "01 44 85 37 01",
    },
  },
  {
    id: "asso-4",
    name: "Académie du Climat",
    legalIdentity: "Ville de Paris - Académie du Climat (équipement municipal)",
    kind: "association",
    types: ["environnemental", "social"],
    isFeatured: true,
    featuredReason: "Le hub de l'engagement citoyen et du climat au cœur de Paris.",
    description:
      "Lieu d'engagement climat ouvert au public: ateliers, débats, formations, programmation régulière et réseau citoyen.",
    location: "Paris 4e",
    lat: 48.8569,
    lng: 2.3564,
    websiteUrl: "https://www.academieduclimat.paris/",
    instagramUrl: "https://www.instagram.com/academieduclimat/",
    coveredArrondissements: [1, 2, 3, 4, 11, 12],
    contributionTypes: ["accueil", "logistique", "communication"],
    tags: ["Climat", "Sensibilisation", "Quartier"],
    availability: "Lundi au samedi, 9h-fin de soiree, agenda ateliers mis à jour régulièrement",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.academieduclimat.paris/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-17",
    recentActivityAt: "2026-04-16",
  },
  {
    id: "asso-shakirail",
    name: "Le Shakirail",
    legalIdentity: "Collectif Curry Vavart / AGETA",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Tiers-lieu artistique, solidaire et culturel du 18e arrondissement, avec ateliers partagés, jardins, résidences et actions de quartier.",
    location: "Paris 18e",
    lat: 48.8923,
    lng: 2.3581,
    websiteUrl: "https://shakirail.curry-vavart.com/",
    coveredArrondissements: [18],
    contributionTypes: ["accueil", "logistique", "communication"],
    tags: ["Tiers-lieu", "Culture", "Jardins", "Quartier"],
    availability: "Selon programmation, ateliers et événements réguliers",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://shakirail.curry-vavart.com/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    associationProfile: {
      mission:
        "Tiers-lieu culturel et solidaire géré collectivement, avec ateliers partagés, jardins, résidences et actions de quartier.",
      recurringNeeds: ["Relais de communication", "Matériel", "Bénévoles d'accueil"],
      pastActions: [
        "Ateliers partagés et résidences artistiques",
        "Jardins partagés, recyclerie et matériauthèque",
        "Portes ouvertes et animations de quartier",
      ],
      usefulResources: [
        {
          label: "Site officiel",
          description: "Programmation, ateliers et appels à projets du lieu.",
          url: "https://shakirail.curry-vavart.com/",
        },
      ],
      publicCalls: [
        {
          type: "communication",
          label: "Relais de communication",
          detail: "Diffusion des événements, appels à participation et portes ouvertes.",
        },
        {
          type: "benevoles",
          label: "Appel à bénévoles",
          detail: "Appui aux événements, aux chantiers participatifs et à la vie du lieu.",
        },
      ],
      impactHistory: {
        actionCount: 24,
        zonesCovered: 1,
        recurrence: "Programmation régulière",
        lastActionAt: "2026-05-20",
        note: "Lieu culturel et solidaire implanté dans le 18e arrondissement.",
      },
      structureStatus: "active_validated",
    },
    lastUpdatedAt: "2026-05-23",
    recentActivityAt: "2026-05-20",
  },
  {
    id: "asso-featured-1",
    name: "Brigade Verte Paris 19",
    legalIdentity: "Brigade Verte (Association Loi 1901)",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Action terrain exemplaire sur la propreté urbaine et le recyclage.",
    description: "Mobilisation citoyenne active pour la propreté et la biodiversité dans le 19ème arrondissement.",
    location: "Paris 19e",
    lat: 48.883,
    lng: 2.385,
    websiteUrl: "https://www.facebook.com/BrigadeVerte19/",
    coveredArrondissements: [19],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Action terrain", "Propreté urbaine", "Quartier"],
    availability: "Sorties hebdomadaires",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-20",
    recentActivityAt: "2026-04-20",
  },
  {
    id: "asso-featured-2",
    name: "Association Sans Murs Paris 15",
    legalIdentity: "Sans Murs (RNA W751245678)",
    kind: "association",
    types: ["social", "humanitaire"],
    isFeatured: true,
    featuredReason: "Pionnier de l'aide alimentaire et sociale de proximité.",
    description: "Soutien aux plus démunis via des distributions alimentaires et un accompagnement social sans conditions.",
    location: "Paris 15e",
    lat: 48.841,
    lng: 2.298,
    websiteUrl: "https://sansmurs.org/",
    coveredArrondissements: [15],
    contributionTypes: ["accueil", "logistique"],
    tags: ["Social", "Action terrain", "Quartier"],
    availability: "7j/7 en soirée",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-22",
    recentActivityAt: "2026-04-22",
  },
  {
    id: "asso-featured-6",
    name: "Fondation de la Mer",
    legalIdentity: "Fondation de la Mer (Reconnue d'Utilité Publique)",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Acteur majeur de la protection des océans et de la biodiversité marine.",
    description: "Soutient des centaines de projets locaux pour la protection du littoral et la sensibilisation océanique.",
    location: "Paris 7e",
    lat: 48.855,
    lng: 2.315,
    websiteUrl: "https://www.fondationdelamer.org/",
    coveredArrondissements: [7],
    contributionTypes: ["financement", "communication"],
    tags: ["Littoral", "Climat", "Partenaire clé"],
    availability: "9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-10",
    recentActivityAt: "2026-04-10",
  },
  {
    id: "asso-zd-greenminded",
    name: "GreenMinded",
    legalIdentity: "GreenMinded (Association / Auto-entrepreneur)",
    kind: "association",
    types: ["environnemental"],
    description: "Association de sensibilisation zéro-déchet, zéro-mégot et pollution plastique. Ateliers, interventions scolaires et sensibilisation grand public.",
    location: "Paris",
    lat: 48.86,
    lng: 2.34,
    websiteUrl: "https://www.greenminded.fr",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    contributionTypes: ["communication", "accueil", "materiel"],
    tags: ["Zéro déchet", "Sensibilisation", "Plastique", "Éducation"],
    availability: "Selon planning",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "asso-gestes-propres",
    name: "Gestes Propres",
    legalIdentity: "Gestes Propres (association nationale)",
    kind: "association",
    scope: "national",
    types: ["environnemental", "social"],
    isFeatured: true,
    featuredReason: "Association nationale utile pour les relais, la diffusion et la mobilisation d'antennes locales.",
    description:
      "Association nationale dédiée à la sensibilisation, aux relais de terrain et à l'appui des collectifs locaux partout en France.",
    location: "France",
    lat: 46.603354,
    lng: 1.888334,
    coveredArrondissements: [],
    contributionTypes: ["communication", "logistique", "accueil"],
    tags: ["National", "Relais", "France"],
    availability: "Couverture nationale avec relais locaux",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "du-1",
    name: "Diplôme Universitaire Engagement",
    legalIdentity: "Sorbonne Université - Diplôme Universitaire Engagement",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Formation de Sorbonne Université pour les acteurs engagés, étudiantes, professionnels et acteurs associatifs. Ce DU a permis d'initier le site web CleanMyMap en structurant le projet et le lien entre mobilisation citoyenne et territoires.",
    location: "Paris 5e",
    lat: 48.8489,
    lng: 2.3431,
    websiteUrl: "https://www.sorbonne-universite.fr/formation/",
    coveredArrondissements: [5],
    contributionTypes: ["communication", "accueil"],
    availability: "Semaines universitaires, 9h-18h. Dossier et inscriptions à consulter en ligne selon sessions annuelles.",
    primaryChannel: {
      platform: "site web",
      label: "Page Sorbonne Université",
      url: "https://www.sorbonne-universite.fr/formation/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-24",
    recentActivityAt: "2026-04-24",
  },
  {
    id: "asso-surfrider-paris",
    name: "Surfrider Paris",
    legalIdentity: "Surfrider Foundation Europe - Bureau Paris (Association Loi 1901)",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Groupe local actif à Paris, avec collectes et Initiatives Océanes urbaines.",
    description: "Association européenne de protection de l'océan et du littoral. À Paris, le groupe local organise des collectes de déchets sur les berges de Seine et mobilize pour les Initiatives Océanes urbaines.",
    location: "Paris",
    lat: 48.86,
    lng: 2.34,
    websiteUrl: "https://surfrider-paris.fr",
    instagramUrl: "https://www.instagram.com/surfriderparis/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    contributionTypes: ["materiel", "logistique", "communication"],
    tags: ["Océan", "Plastic", "Collecte", "Sensibilisation"],
    availability: "Collectes régulières + événements ponctuels",
    primaryChannel: {
      platform: "site web",
      label: "Site Paris",
      url: "https://surfrider-paris.fr",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "asso-zerowaste-paris",
    name: "Zero Waste Paris",
    legalIdentity: "Association Zero Waste France - Groupe local Paris",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Association zéro déchet active à Paris et en Île-de-France. Très utile pour la réduction à la source, pas seulement le ramassage.",
    description: "Groupe local de Zero Waste France militant pour la réduction des déchets à la source. Ateliers, sensibilisation, plaidoyer et actions de terrain pour promouvoir le zéro déchet dans la capitale.",
    location: "Paris",
    lat: 48.87,
    lng: 2.36,
    websiteUrl: "https://www.zerowasteparis.fr",
    instagramUrl: "https://www.instagram.com/zerowasteparis/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["communication", "accueil", "materiel"],
    tags: ["Zéro déchet", "Réduction", "Sensibilisation", "Mode"],
    availability: "Ateliers mensuels + événements ponctuels",
    primaryChannel: {
      platform: "site web",
      label: "Site local",
      url: "https://www.zerowasteparis.fr",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
];

export const ASSOCIATIONS_ENTRIES: AnnuaireEntry[] = ASSOCIATIONS_BASE_ENTRIES.map(
  (entry) => ({
    ...entry,
    associationProfile: ASSOCIATION_PROFILES[entry.id] ?? entry.associationProfile,
  }),
);
