import type {
  AnnuaireEntrySeedInput,
} from "@/lib/partners/annuaire-types";

export const ASSOCIATIONS_ENTRIES: AnnuaireEntrySeedInput[] = [
  {
    id: "asso-1",
    name: "Pik Pik Environnement",
    legalIdentity: "Association Pik Pik Environnement (SIREN 803 350 367)",
    kind: "association",
    types: ["environnemental", "social"],
    description:
      "Accompagne les Francilien·ne·s dans la transition écologique avec des ateliers terrain.",
    location: "Issy-les-Moulineaux",
    lat: 48.825,
    lng: 2.27,
    websiteUrl: "https://www.pikpik.org/",
    instagramUrl: "https://www.instagram.com/pikpik_environnement/",
    coveredArrondissements: [15, 16],
    contributionTypes: ["materiel", "communication"],
    availability: "Lundi au samedi, 10h-18h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/pikpik_environnement/",
    },
    lastUpdatedAt: "2026-04-12",
    internalAdminContact: {
      referentName: "Kamera Vesic",
      email: "contact@pikpik.org",
      phone: "01 41 46 05 00",
    },
  },
  {
    id: "asso-2",
    name: "Le Carillon / La Cloche",
    legalIdentity: "Association La Cloche (RNA W751221768)",
    kind: "association",
    types: ["social", "humanitaire"],
    description:
      "Réseau solidaire de commerçant·e·s engagé·e·s pour aider les personnes sans domicile.",
    location: "Paris Centre",
    lat: 48.86,
    lng: 2.35,
    websiteUrl: "https://lacloche.org/le-carillon",
    instagramUrl: "https://www.instagram.com/assolacloche/",
    coveredArrondissements: [1, 2, 3, 4, 10, 11],
    contributionTypes: ["accueil", "logistique", "communication"],
    availability: "Tous les jours, 9h-20h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/assolacloche/",
    },
    lastUpdatedAt: "2026-04-13",
    internalAdminContact: {
      referentName: "Valerie Fayard",
      email: "valerie.fayard@lacloche.org",
      phone: "Non publié",
    },
  },
  {
    id: "asso-3",
    name: "Carton Plein",
    legalIdentity: "Association Carton Plein (RNA W751216999)",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Inclusion sociale et réemploi via déménagements à vélo et logistique locale.",
    location: "Paris 11e / 18e",
    lat: 48.89,
    lng: 2.355,
    websiteUrl: "https://www.cartonplein.org/",
    instagramUrl: "https://www.instagram.com/cartonplein_org/",
    coveredArrondissements: [11, 18, 19, 20],
    contributionTypes: ["logistique", "materiel", "accueil"],
    availability: "Sur demande + créneaux hebdomadaires",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.cartonplein.org/",
    },
    lastUpdatedAt: "2026-04-11",
    internalAdminContact: {
      referentName: "Equipe Carton Plein",
      email: "bonjour@cartonplein.org",
      phone: "01 44 85 37 01",
    },
  },
  {
    id: "asso-4",
    name: "Académie du Climat",
    legalIdentity: "Ville de Paris - Académie du Climat (équipement municipal)",
    kind: "association",
    types: ["environnemental", "social"],
    isFeatured: true,
    featuredReason: "Le hub de l'engagement citoyen et du climat au cœur de Paris.",
    description:
      "Lieu d'engagement climat ouvert au public: ateliers, débats, formations, programmation régulière et réseau citoyen.",
    location: "Paris 4e",
    lat: 48.8569,
    lng: 2.3564,
    websiteUrl: "https://www.academieduclimat.paris/",
    instagramUrl: "https://www.instagram.com/academieduclimat/",
    coveredArrondissements: [1, 2, 3, 4, 11, 12],
    contributionTypes: ["accueil", "logistique", "communication"],
    tags: ["Climat", "Sensibilisation", "Quartier"],
    availability: "Lundi au samedi, 9h-fin de soiree, agenda ateliers mis à jour régulièrement",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.academieduclimat.paris/",
    },
    lastUpdatedAt: "2026-04-17",
  },
  {
    id: "asso-shakirail",
    name: "Le Shakirail",
    legalIdentity: "Collectif Curry Vavart / AGETA",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Tiers-lieu artistique, solidaire et culturel du 18e arrondissement, avec ateliers partagés, jardins, résidences et actions de quartier.",
    location: "Paris 18e",
    lat: 48.8923,
    lng: 2.3581,
    websiteUrl: "https://shakirail.curry-vavart.com/",
    coveredArrondissements: [18],
    contributionTypes: ["accueil", "logistique", "communication"],
    tags: ["Tiers-lieu", "Culture", "Jardins", "Quartier"],
    availability: "Selon programmation, ateliers et événements réguliers",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://shakirail.curry-vavart.com/",
    },
    lastUpdatedAt: "2026-05-23",
  },
  {
    id: "asso-featured-1",
    name: "Brigade Verte Paris 19",
    legalIdentity: "Brigade Verte (Association Loi 1901)",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Ressource locale consacrée à la propreté urbaine et au recyclage.",
    description: "Ressource locale sur la propreté et la biodiversité dans le 19e arrondissement.",
    location: "Paris 19e",
    lat: 48.883,
    lng: 2.385,
    websiteUrl: "https://www.facebook.com/BrigadeVerte19/",
    coveredArrondissements: [19],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Propreté urbaine", "Quartier"],
    availability: "Non précisée",
    lastUpdatedAt: "2026-04-20",
  },
  {
    id: "asso-featured-2",
    name: "Association Sans Murs Paris 15",
    legalIdentity: "Association Sans Murs",
    kind: "association",
    types: ["social", "humanitaire"],
    isFeatured: true,
    featuredReason: "Ressource locale d'entraide et de bénévolat de quartier.",
    description: "Association locale de bénévolat et d'entraide de quartier.",
    location: "Paris 15e",
    lat: 48.841,
    lng: 2.298,
    websiteUrl: "https://sansmurs.org/",
    coveredArrondissements: [15],
    contributionTypes: ["accueil", "logistique"],
    tags: ["Social", "Quartier"],
    availability: "7j/7 en soirée",
    lastUpdatedAt: "2026-04-22",
  },
  {
    id: "asso-featured-6",
    name: "Fondation de la Mer",
    legalIdentity: "Fondation de la Mer",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Missions de protection des océans et de la biodiversité marine.",
    description: "Missions de protection de l'Océan et soutien à des acteurs de terrain.",
    location: "Paris 7e",
    lat: 48.855,
    lng: 2.315,
    websiteUrl: "https://www.fondationdelamer.org/",
    coveredArrondissements: [7],
    contributionTypes: ["financement", "communication"],
    tags: ["Littoral", "Climat"],
    availability: "9h-18h",
    lastUpdatedAt: "2026-04-10",
  },
  {
    id: "asso-zd-greenminded",
    name: "GreenMinded",
    legalIdentity: "GreenMinded (Association / Auto-entrepreneur)",
    kind: "association",
    types: ["environnemental"],
    description: "Association de sensibilisation zéro-déchet, zéro-mégot et pollution plastique. Ateliers, interventions scolaires et sensibilisation grand public.",
    location: "Paris",
    lat: 48.86,
    lng: 2.34,
    websiteUrl: "https://www.greenminded.fr",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    contributionTypes: ["communication", "accueil", "materiel"],
    tags: ["Zéro déchet", "Sensibilisation", "Plastique", "Éducation"],
    availability: "Selon planning",
    lastUpdatedAt: "2026-05-01",
  },
  {
    id: "asso-gestes-propres",
    name: "Gestes Propres",
    legalIdentity: "Gestes Propres (association nationale)",
    kind: "association",
    scope: "national",
    types: ["environnemental", "social"],
    isFeatured: true,
    featuredReason: "Ressource nationale sur les relais et la diffusion locale.",
    description:
      "Association nationale dédiée à la sensibilisation, aux relais de terrain et à l'appui des collectifs locaux partout en France.",
    location: "France",
    lat: 46.603354,
    lng: 1.888334,
    coveredArrondissements: [],
    contributionTypes: ["communication", "logistique", "accueil"],
    tags: ["National", "Relais", "France"],
    availability: "Couverture nationale avec relais locaux",
    lastUpdatedAt: "2026-05-01",
  },
  {
    id: "asso-pepite",
    name: "Pépite Sorbonne Université",
    legalIdentity: "PEPITE - réseau national de l'entrepreneuriat étudiant",
    kind: "association",
    scope: "national",
    types: ["social"],
    isFeatured: true,
    featuredReason: "Ressource de Sorbonne Université pour l'entrepreneuriat étudiant.",
    description:
      "Réseau national dédié à l'entrepreneuriat étudiant, avec un relais local à Sorbonne Université pour accompagner les porteurs de projet.",
    location: "France / Paris 5e",
    lat: 48.8489,
    lng: 2.3431,
    websiteUrl: "https://pepite.sorbonne-universite.fr/",
    coveredArrondissements: [5],
    contributionTypes: ["communication", "accueil"],
    tags: ["Entrepreneuriat étudiant", "Réseau national", "Sorbonne Université"],
    availability: "Selon les dispositifs et les accompagnements du réseau",
    primaryChannel: {
      platform: "site web",
      label: "Page Pépite de Sorbonne Université",
      url: "https://pepite.sorbonne-universite.fr/",
    },
    lastUpdatedAt: "2026-05-01",
  },
  {
    id: "du-1",
    name: "Diplôme Universitaire Engagement",
    legalIdentity: "Sorbonne Université - Diplôme Universitaire Engagement",
    kind: "association",
    types: ["social", "environnemental"],
    description:
      "Formation de Sorbonne Université pour les acteurs engagés, étudiantes, professionnels et acteurs associatifs. Ce DU a permis d'initier le site web CleanMyMap en structurant le projet et le lien entre mobilisation citoyenne et territoires.",
    location: "Paris 5e",
    lat: 48.8489,
    lng: 2.3431,
    websiteUrl: "https://www.sorbonne-universite.fr/formation/",
    coveredArrondissements: [5],
    contributionTypes: ["communication", "accueil"],
    availability: "Semaines universitaires, 9h-18h. Dossier et inscriptions à consulter en ligne selon sessions annuelles.",
    primaryChannel: {
      platform: "site web",
      label: "Page Sorbonne Université",
      url: "https://www.sorbonne-universite.fr/formation/",
    },
    lastUpdatedAt: "2026-04-24",
  },
  {
    id: "asso-surfrider-paris",
    name: "Surfrider Paris",
    legalIdentity: "Surfrider Foundation Europe - Bureau Paris (Association Loi 1901)",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Ressource locale sur la protection de l'océan et du littoral.",
    description: "Association européenne de protection de l'océan et du littoral. À Paris, le groupe local organise des collectes de déchets sur les berges de Seine et mobilize pour les Initiatives Océanes urbaines.",
    location: "Paris",
    lat: 48.86,
    lng: 2.34,
    websiteUrl: "https://surfrider-paris.fr",
    instagramUrl: "https://www.instagram.com/surfriderparis/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    contributionTypes: ["materiel", "logistique", "communication"],
    tags: ["Océan", "Plastic", "Collecte", "Sensibilisation"],
    availability: "Collectes régulières + événements ponctuels",
    primaryChannel: {
      platform: "site web",
      label: "Site Paris",
      url: "https://surfrider-paris.fr",
    },
    lastUpdatedAt: "2026-05-01",
  },
  {
    id: "asso-zerowaste-paris",
    name: "Zero Waste Paris",
    legalIdentity: "Association Zero Waste France - Groupe local Paris",
    kind: "association",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Ressource locale sur la réduction des déchets à la source.",
    description: "Groupe local de Zero Waste France militant pour la réduction des déchets à la source. Ateliers, sensibilisation, plaidoyer et actions de terrain pour promouvoir le zéro déchet dans la capitale.",
    location: "Paris",
    lat: 48.87,
    lng: 2.36,
    websiteUrl: "https://www.zerowasteparis.fr",
    instagramUrl: "https://www.instagram.com/zerowasteparis/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["communication", "accueil", "materiel"],
    tags: ["Zéro déchet", "Réduction", "Sensibilisation", "Mode"],
    availability: "Ateliers mensuels + événements ponctuels",
    primaryChannel: {
      platform: "site web",
      label: "Site local",
      url: "https://www.zerowasteparis.fr",
    },
    lastUpdatedAt: "2026-05-01",
  },
];
