import type { AnnuaireEntry } from "../annuaire-map-canvas";

export const ENTREPRISES_ENTRIES: AnnuaireEntry[] = [
  {
    id: "com-1",
    name: "La Textilerie",
    legalIdentity: "SAS La Textilerie (SIREN 824 531 417)",
    kind: "commerce",
    types: ["environnemental", "social"],
    description:
      "Tiers-lieu mode responsable : friperie, couture, ateliers de sensibilisation.",
    location: "Paris 10e",
    lat: 48.875,
    lng: 2.36,
    websiteUrl: "https://latextilerie.fr/",
    instagramUrl: "https://www.instagram.com/latextilerieparis/",
    coveredArrondissements: [9, 10, 11],
    contributionTypes: ["accueil", "materiel", "communication"],
    availability: "Mardi au dimanche, 11h-19h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/latextilerieparis/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-15",
    recentActivityAt: "2026-04-14",
    internalAdminContact: {
      referentName: "Elsa Monsegur",
      email: "contact@latextilerie.fr",
      phone: "01 40 35 77 14",
    },
  },
  {
    id: "asso-featured-3",
    name: "ALCOME",
    legalIdentity: "Eco-organisme ALCOME (Mégots)",
    kind: "entreprise",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Eco-organisme dédié à la réduction des déchets de mégots de cigarettes.",
    description: "Accompagne les communes pour réduire la présence de mégots dans l'espace public via le recyclage et la sensibilisation.",
    location: "France / Paris",
    lat: 48.87,
    lng: 2.32,
    websiteUrl: "https://www.alcome.fr/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["financement", "materiel"],
    tags: ["Mégots", "Propreté urbaine", "Partenaire clé"],
    availability: "Bureaux 9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-25",
    recentActivityAt: "2026-04-25",
  },
  {
    id: "asso-featured-4",
    name: "Tchao Mégot",
    legalIdentity: "Tchao Mégot SAS (Économie Circulaire)",
    kind: "entreprise",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Innovation brevetée pour le dépolluage et recyclage des mégots sans eau.",
    description: "Première solution écologique de recyclage de mégots transformés en isolant thermique.",
    location: "National / Paris",
    lat: 48.85,
    lng: 2.33,
    websiteUrl: "https://tchaomegot.com/",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "Innovation", "Action terrain"],
    availability: "9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-18",
    recentActivityAt: "2026-04-18",
  },
  {
    id: "asso-featured-5",
    name: "Cy-Clope",
    legalIdentity: "Cy-Clope SAS",
    kind: "entreprise",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Leader de la collecte et valorisation des mégots en entreprise.",
    description: "Installation de cendriers connectés et gestion déléguée des zones fumeurs pour les professionnels.",
    location: "Saint-Ouen / Paris",
    lat: 48.91,
    lng: 2.33,
    websiteUrl: "https://www.cy-clope.fr/",
    coveredArrondissements: [8, 9, 17],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "Entreprise", "Propreté urbaine"],
    availability: "9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-15",
    recentActivityAt: "2026-04-15",
  },
  {
    id: "asso-megots-alcome",
    name: "ALCOME",
    legalIdentity: "Éco-organisme ALCOME (Agrément ministerial)",
    kind: "entreprise",
    types: ["environnemental"],
    isFeatured: true,
    featuredReason: "Éco-organisme dédié à la réduction des déchets de mégots de cigarettes.",
    description: "Accompagne les collectivités, associations et entreprises pour réduire la présence de mégots dans l'espace public via le recyclage et la sensibilisation. Distribution de cendriers de poche.",
    location: "France / Paris",
    lat: 48.87,
    lng: 2.32,
    websiteUrl: "https://www.alcome.eco",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["financement", "materiel", "communication"],
    tags: ["Mégots", "Eco-organisme", "Collectivités", "Sensibilisation"],
    availability: "Bureaux 9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "asso-megots-ecomegot",
    name: "Écomégot",
    legalIdentity: "Écomégot SAS (Économie circulaire)",
    kind: "entreprise",
    types: ["environnemental"],
    description: "Service de collecte et recyclage de mégots spécialisé pour les événements et cleanups spécialisés. Orientation utile pour les collectes ciblées.",
    location: "France / Paris",
    lat: 48.85,
    lng: 2.35,
    websiteUrl: "https://www.ecomegot.com",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "Recyclage", "Événements", "Collecte spécialisée"],
    availability: "Sur rendez-vous",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "asso-megots-cyclope",
    name: "Cy-Clope",
    legalIdentity: "Cy-Clope SAS",
    kind: "entreprise",
    types: ["environnemental"],
    description: "Solution de collecte et recyclage des mégots pour entreprises et lieux publics. Installation de cendriers connectés et gestion déléguée des zones fumeurs.",
    location: "Saint-Ouen / Paris",
    lat: 48.91,
    lng: 2.33,
    websiteUrl: "https://www.cy-clope.fr",
    coveredArrondissements: [8, 9, 17],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "Entreprise", "Cendriers connectés", "Propreté urbaine"],
    availability: "9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "asso-megots-tchaomegot",
    name: "TchaoMegot",
    legalIdentity: "Tchao Megot SAS (Économie Circulaire)",
    kind: "entreprise",
    types: ["environnemental"],
    description: "Collecte et recyclage de mégots, plutôt orienté B2B et collectivités. Innovation brevetée pour le dépolluage et recyclage des mégots sans eau.",
    location: "National / Paris",
    lat: 48.85,
    lng: 2.33,
    websiteUrl: "https://tchaomegot.com",
    coveredArrondissements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    contributionTypes: ["materiel", "logistique"],
    tags: ["Mégots", "B2B", "Collectivités", "Innovation"],
    availability: "9h-18h",
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-05-01",
    recentActivityAt: "2026-05-01",
  },
  {
    id: "com-2",
    name: "La Collecterie Paris",
    legalIdentity: "Association La Collecterie (RNA W931014584)",
    kind: "commerce",
    types: ["environnemental", "social"],
    description:
      "Ressourcerie locale avec ateliers de réemploi et collecte de matériel.",
    location: "Montreuil",
    lat: 48.86,
    lng: 2.43,
    websiteUrl: "https://lacollecterie.org/",
    instagramUrl: "https://www.instagram.com/lacollecterie/",
    coveredArrondissements: [19, 20],
    contributionTypes: ["materiel", "logistique", "financement"],
    availability: "Mercredi au dimanche, 10h-18h",
    primaryChannel: {
      platform: "instagram",
      label: "Compte Instagram",
      url: "https://www.instagram.com/lacollecterie/",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-08",
    recentActivityAt: "2026-04-05",
  },
  {
    id: "com-3",
    name: "Klin d'oeil",
    legalIdentity: "Klin d'oeil, boutique de createurs et ateliers artistiques (Bas Belleville, rue Deguerry, Paris 11e)",
    kind: "commerce",
    types: ["social"],
    description:
      "Boutique de createurs et lieu d'activites artistiques implante a Bas Belleville, au croisement des 11e, 19e et 20e arrondissements, avec une carte des bonnes adresses pour valoriser le quartier.",
    location: "Bas Belleville, rue Deguerry, Paris 11e",
    lat: 48.8667,
    lng: 2.3788,
    websiteUrl: "https://klindoeil.com",
    coveredArrondissements: [11, 19, 20],
    contributionTypes: ["accueil", "communication"],
    availability: "Selon programmation des ateliers et temps boutique",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://klindoeil.com",
    },
    verificationStatus: "verifie",
    qualificationStatus: "partenaire_actif",
    lastUpdatedAt: "2026-04-23",
    recentActivityAt: "2026-04-22",
  },
  {
    id: "ent-1",
    name: "Green Flex",
    legalIdentity: "Green Flex SAS (SIREN 912 540 881)",
    kind: "entreprise",
    types: ["environnemental"],
    description:
      "Accompagne les entreprises pour financer et opérer des actions locales.",
    location: "Paris 9e",
    lat: 48.874,
    lng: 2.333,
    coveredArrondissements: [8, 9, 10],
    contributionTypes: ["financement", "logistique", "communication"],
    availability: "Du lundi au vendredi, 9h-18h",
    primaryChannel: {
      platform: "site web",
      label: "Site officiel",
      url: "https://www.greenflex.com/",
    },
    verificationStatus: "a_revalider",
    qualificationStatus: "contact_non_qualifie",
    lastUpdatedAt: "2026-04-23",
    recentActivityAt: "2026-04-22",
  },
];
