import type { OrganizerDirectoryEntry } from "./organizer-directory-contract";

export const ORGANIZER_DIRECTORY_VERIFIED_AT = "2026-09-06" as const;

export const ORGANIZER_DIRECTORY_NATIONAL = [
  // ---------------------------------------------------------------------------
  // ENTREPRISES — activité récurrente de cleanwalk documentée
  // ---------------------------------------------------------------------------
  {
    id: "company-matmut",
    name: "Groupe Matmut",
    value: "Entreprise - Groupe Matmut",
    organizerType: "company",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "direct_organizer",
    websiteUrl:
      "https://www.matmut.fr/groupe-matmut/nos-engagements/cleanwalks-matmut.html",
    activityEvidenceUrls: [
      "https://www.matmut.fr/groupe-matmut/nos-engagements/cleanwalks-matmut.html",
      "https://www.matmut.fr/groupe-matmut/lagenda/2026/cleanwalks-06-06-2026.html",
    ],
    activityEvidenceSummary:
      "5e édition nationale des Cleanwalks Matmut en 2026, avec 10 villes dont Paris, après quatre éditions précédentes.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "company-decathlon",
    name: "Decathlon",
    value: "Entreprise - Decathlon",
    organizerType: "company",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "direct_organizer",
    websiteUrl:
      "https://activites.decathlon.fr/fr-FR/d/world-clean-up-day-decathlon",
    activityEvidenceUrls: [
      "https://activites.decathlon.fr/fr-FR/d/world-clean-up-day-decathlon",
      "https://activites.decathlon.fr/fr-FR/activites-sportives/details/12911431",
      "https://activites.decathlon.fr/fr-FR/activites-sportives/details/6524242",
    ],
    activityEvidenceSummary:
      "World Cleanup Day organisé via plusieurs magasins en 2025 puis à nouveau en 2026 ; le dispositif est proposé à l'échelle nationale.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },

  {
    id: "company-eleclerc",
    name: "E.Leclerc — Nettoyons la Nature",
    value: "Entreprise - E.Leclerc",
    organizerType: "company",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: "Mouvement E.Leclerc",
    activityCadence: "annual",
    activityRole: "direct_organizer",
    websiteUrl: "https://www.mouvement.leclerc/nettoyons-la-nature",
    activityEvidenceUrls: [
      "https://www.mouvement.leclerc/nettoyons-la-nature",
      "https://mouvement.leclerc/espace-presse/eleclerc-lance-la-29eme-edition-de-loperation-nettoyons-la-nature-ouverture-des",
    ],
    activityEvidenceSummary:
      "29e édition nationale de Nettoyons la Nature en septembre 2026 ; l'opération est organisée chaque année par les Centres E.Leclerc partout en France.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },

  // ---------------------------------------------------------------------------
  // ASSOCIATIONS — portée nationale
  // ---------------------------------------------------------------------------
  {
    id: "association-world-cleanup-day-france",
    name: "World Cleanup Day France",
    value: "World Cleanup Day France",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "both",
    websiteUrl: "https://www.worldcleanupday.fr/",
    activityEvidenceUrls: [
      "https://www.worldcleanupday.fr/",
      "https://www.worldcleanupday.fr/en-france/",
      "https://www.worldcleanupday.fr/foire-aux-questions/",
    ],
    activityEvidenceSummary:
      "Mobilisation nationale de ramassage fixée au 20 septembre chaque année, complétée par le Mégothon et un réseau d'ambassadeurs sur le territoire.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-surfrider",
    name: "Surfrider Foundation Europe / Surfrider France",
    value: "Surfrider Foundation Europe / Surfrider France",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "both",
    websiteUrl: "https://www.surfrider.fr/",
    activityEvidenceUrls: [
      "https://www.surfrider.fr/devenir-benevole/",
      "https://www.surfrider.fr/press/surfrider-lance-retrace-un-programme-de-sciences-participatives-sur-les-dechets/",
      "https://retrace.surfrider.eu/projet/",
    ],
    activityEvidenceSummary:
      "Collectes de déchets organisées depuis 1995 ; 17 172 participants en 2025 et poursuite du programme sous RETRACE en 2026.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-cleanwalker",
    name: "CleanWalker",
    value: "CleanWalker",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "direct_organizer",
    websiteUrl: "https://cleanwalker.fr/",
    activityEvidenceUrls: [
      "https://cleanwalker.fr/agenda/",
      "https://cleanwalker.fr/nos-antennes/",
      "https://cleanwalker.fr/association/",
    ],
    activityEvidenceSummary:
      "Cleanwalks organisées toute l'année via un réseau d'antennes ; agenda 2026 actif avec plusieurs opérations en Essonne et Seine-et-Marne.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-greenminded",
    name: "GreenMinded",
    value: "GreenMinded",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "both",
    websiteUrl: "https://www.greenminded.fr/",
    activityEvidenceUrls: [
      "https://www.greenminded.fr/ramassages-de-dechets/",
      "https://www.jeveuxaider.gouv.fr/missions-benevolat/20109/benevolat-greenminded",
      "https://www.jeveuxaider.gouv.fr/missions-benevolat/81710/benevolat-greenminded-104",
    ],
    activityEvidenceSummary:
      "Organisation et accompagnement de ramassages partout en France, avec opérations en Île-de-France et missions de coordination récurrentes.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-wings-of-the-ocean",
    name: "Wings of the Ocean",
    value: "Wings of the Ocean",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "direct_organizer",
    websiteUrl: "https://www.wingsoftheocean.com/",
    activityEvidenceUrls: [
      "https://www.wingsoftheocean.com/s-informer/nos-evenements/",
      "https://www.wingsoftheocean.com/nos-missions/",
      "https://donate.wingsoftheocean.com/",
    ],
    activityEvidenceSummary:
      "Nombreux ramassages documentés en 2026 dans plusieurs villes françaises, avec missions et collecte de données de déchets à l'échelle nationale.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-project-rescue-ocean",
    name: "Project Rescue Ocean",
    value: "Project Rescue Ocean",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "direct_organizer",
    websiteUrl: "https://projectrescueocean.org/",
    activityEvidenceUrls: [
      "https://projectrescueocean.org/",
      "https://projectrescueocean.org/actualites-project-rescue-ocean/",
    ],
    activityEvidenceSummary:
      "Réseau d'opérations éco-citoyennes avec plusieurs actions de dépollution programmées et réalisées en France en 2026.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-merterre",
    name: "MerTerre",
    value: "MerTerre",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "both",
    websiteUrl: "https://mer-terre.org/",
    activityEvidenceUrls: [
      "https://mer-terre.org/zero-dechet-sauvage/",
      "https://mer-terre.org/adopt1-spot/",
      "https://mer-terre.org/calanques-propres/",
    ],
    activityEvidenceSummary:
      "Coordination nationale de Zéro Déchet Sauvage ; le programme Adopt'1 Spot demande trois ramassages par an et MerTerre coordonne aussi des opérations de terrain.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-mountain-riders",
    name: "Mountain Riders",
    value: "Mountain Riders",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "both",
    websiteUrl: "https://www.mountain-riders.org/",
    activityEvidenceUrls: [
      "https://www.mountain-riders.org/montagne-zero-dechet/les-premices/",
      "https://www.mountain-riders.org/montagne-zero-dechet/charte-mon/",
    ],
    activityEvidenceSummary:
      "Campagne nationale de ramassage en montagne reconduite chaque année ; 89 opérations caractérisées en 2025 et campagne 2026 active.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-team-river-clean",
    name: "Team River Clean",
    value: "Team River Clean",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "multiple_per_year",
    activityRole: "direct_organizer",
    websiteUrl: "https://teamriverclean.org/",
    activityEvidenceUrls: [
      "https://teamriverclean.org/",
      "https://teamriverclean.org/qui-sommes-nous/",
    ],
    activityEvidenceSummary:
      "Mouvement national de nettoyage des rivières, berges et lacs ; plus de 250 journées de ramassage annoncées depuis 2021.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-the-clean-project",
    name: "The Clean Project",
    value: "The Clean Project",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "direct_organizer",
    websiteUrl: "https://www.thecleanproject.fr/",
    activityEvidenceUrls: [
      "https://www.thecleanproject.fr/",
      "https://thecleanproject.fr/",
    ],
    activityEvidenceSummary:
      "12 cleanups documentés en 2024, festival-cleanup à Paris en 2025 et nouvelle édition parisienne ainsi qu'une étape lyonnaise en 2026.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-lopp",
    name: "Ludovic Objectif Planète Propre (LOPP)",
    value: "Ludovic Objectif Planète Propre (LOPP)",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "both",
    websiteUrl: "https://ludovicobjectifplanetepropre.org/",
    activityEvidenceUrls: [
      "https://ludovicobjectifplanetepropre.org/",
      "https://lemegothon.fr/cgu/",
      "https://alcome.eco/nos-associations-partenaires/",
    ],
    activityEvidenceSummary:
      "Association francilienne portant des défis de nettoyage itinérants et éditant la plateforme du Mégothon ; nouveau défi national annoncé à partir de 2026.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },

  {
    id: "association-fnc-jaime-la-nature-propre",
    name: "Fédération Nationale des Chasseurs — J’aime la Nature Propre",
    value: "Fédération Nationale des Chasseurs — J’aime la Nature Propre",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: "Fédération Nationale des Chasseurs",
    activityCadence: "annual",
    activityRole: "both",
    websiteUrl: "https://www.jaimelanaturepropre.fr/",
    activityEvidenceUrls: [
      "https://www.jaimelanaturepropre.fr/",
      "https://www.jaimelanaturepropre.fr/loperation/",
    ],
    activityEvidenceSummary:
      "J’aime la Nature Propre est une opération nationale annuelle portée par la Fédération Nationale des Chasseurs ; 6e édition en 2026 et édition 2027 déjà annoncée.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-no-plastic-in-my-sea",
    name: "No Plastic In My Sea",
    value: "No Plastic In My Sea",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: null,
    activityCadence: "annual",
    activityRole: "both",
    websiteUrl: "https://noplasticinmysea.org/",
    activityEvidenceUrls: [
      "https://noplasticinmysea.org/",
      "https://www.jeveuxaider.gouv.fr/missions-benevolat/101667/benevolat-no-plastic-in-my-sea-13",
      "https://www.fondationdelamer.org/nos-programmes/un-geste-pour-la-mer/associations/no-plastic-in-my-sea/",
    ],
    activityEvidenceSummary:
      "Le No Plastic Challenge est reconduit chaque année ; l'édition 2026 propose explicitement d'organiser des ramassages et plusieurs collectes 2026 sont documentées en France, dont à Paris.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },
  {
    id: "association-defi-environnement-lions-france",
    name: "Défi pour l’Environnement — Lions de France",
    value: "Défi pour l’Environnement — Lions de France",
    organizerType: "association",
    geographicScope: "national",
    city: null,
    region: null,
    isIleDeFrance: null,
    parentOrganization: "Lions de France",
    activityCadence: "multiple_per_year",
    activityRole: "both",
    websiteUrl: "https://defipourlenvironnement.org/",
    activityEvidenceUrls: [
      "https://defipourlenvironnement.org/about-us/?lang=en",
      "https://www.lions-france.org/wp-content/uploads/2025/02/guide-des-assos-2024.pdf",
      "https://lions-seineetmarneenvironnement.myassoc.org/action-defi-77-pour-l-environnement-edition-2026-96203.html",
    ],
    activityEvidenceSummary:
      "Association fédérative des Lions de France qui coordonne des actions de nettoyage de la nature en France ; Défi 77 est reconduit en 2026 pour sa 11e édition.",
    lastVerifiedActivityYear: 2026,
    verifiedAt: ORGANIZER_DIRECTORY_VERIFIED_AT,
  },

  // ---------------------------------------------------------------------------
] as const satisfies readonly OrganizerDirectoryEntry[];
