export const PROTECTED_ROUTE_PATTERNS = [
  "/admin(.*)",
  "/dashboard(.*)",
  "/actions(.*)",
  "/form-comparison(.*)",
  "/sections(.*)",
  "/api/admin(.*)",
  "/api/actions(.*)",
  "/api/account(.*)",
  "/api/community(.*)",
  "/api/chat(.*)",
  "/api/analytics(.*)",
  "/api/pilotage(.*)",
  "/api/partners(.*)",
  "/api/recycling(.*)",
  "/api/reports(.*)",
  "/api/route(.*)",
  "/api/send(.*)",
  "/api/services(.*)",
  "/api/notifications(.*)",
  "/api/spots(.*)",
  "/api/users(.*)",
  "/api/email/test(.*)",
  "/prints(.*)",
  "/sponsor-portal(.*)",
] as const;
