export {
  ENVIRONMENTAL_IMPACT_ESTIMATOR_HYPOTHESES,
  ENVIRONMENTAL_IMPACT_ESTIMATOR_LIMITATIONS,
  ENVIRONMENTAL_IMPACT_ESTIMATOR_VERSION,
  ENVIRONMENTAL_IMPACT_ELECTRICITY_FACTOR,
  ENVIRONMENTAL_IMPACT_WATER_FACTOR,
  ENVIRONMENTAL_IMPACT_CO2E_COMPOSITION_NOTE,
  ENVIRONMENTAL_IMPACT_CHATGPT_EXTENDED_MODE_HOURS_PER_WEEK,
  ENVIRONMENTAL_IMPACT_GRAPH_CONSIDERATIONS,
  ENVIRONMENTAL_IMPACT_INFRASTRUCTURE_HYPOTHESES,
  ENVIRONMENTAL_IMPACT_INFRASTRUCTURE_METRIC_DEFINITIONS,
  ENVIRONMENTAL_IMPACT_INFRASTRUCTURE_NOTES,
  ENVIRONMENTAL_IMPACT_INFRASTRUCTURE_SERVICE_DEFINITIONS,
  ENVIRONMENTAL_IMPACT_LIFECYCLE_AXIS_DEFINITIONS,
  ENVIRONMENTAL_IMPACT_LIFECYCLE_COMPONENT_DEFINITIONS,
  ENVIRONMENTAL_IMPACT_LIFECYCLE_HYPOTHESES,
  ENVIRONMENTAL_IMPACT_PROJECT_ANCHORS,
  ENVIRONMENTAL_IMPACT_POST_DEFINITIONS,
  ENVIRONMENTAL_IMPACT_SECOND_ORDER_FACTOR_DEFINITIONS,
  ENVIRONMENTAL_IMPACT_SECOND_ORDER_HYPOTHESES,
} from "./constants";
export type {
  EnvironmentalImpactEstimateInput,
  EnvironmentalImpactEstimateModel,
  EnvironmentalImpactDashboardResponse,
  EnvironmentalImpactCurveDriverBreakdown,
  EnvironmentalImpactCurveDriverKey,
  EnvironmentalImpactCodexUsageMonthlyEstimate,
  EnvironmentalImpactCodexUsageSource,
  EnvironmentalImpactCodexUsageWeeklyInput,
  EnvironmentalImpactCodexUsageWeeklySnapshotRecord,
  EnvironmentalImpactDataGapNote,
  EnvironmentalImpactEstimatorMethodology,
  EnvironmentalImpactProjectAnchor,
  EnvironmentalImpactGraphEstimate,
  EnvironmentalImpactGraphGranularity,
  EnvironmentalImpactInfrastructureCurvePoint,
  EnvironmentalImpactInfrastructureEstimate,
  EnvironmentalImpactInfrastructureInput,
  EnvironmentalImpactInfrastructureMetricDefinition,
  EnvironmentalImpactInfrastructureMetricEstimate,
  EnvironmentalImpactInfrastructureMetricKey,
  EnvironmentalImpactInfrastructureMetricsInput,
  EnvironmentalImpactInfrastructureServiceDefinition,
  EnvironmentalImpactInfrastructureServiceEstimate,
  EnvironmentalImpactLifecycleAxisDefinition,
  EnvironmentalImpactLifecycleAxisEstimate,
  EnvironmentalImpactLifecycleAxisKey,
  EnvironmentalImpactLifecycleComponentDefinition,
  EnvironmentalImpactLifecycleComponentEstimate,
  EnvironmentalImpactLifecycleComponentKey,
  EnvironmentalImpactLifecycleEstimate,
  EnvironmentalImpactSecondOrderEstimate,
  EnvironmentalImpactSecondOrderFactorDefinition,
  EnvironmentalImpactSecondOrderFactorEstimate,
  EnvironmentalImpactSecondOrderFactorKey,
  EnvironmentalImpactElectricityCalculation,
  EnvironmentalImpactElectricityEstimate,
  EnvironmentalImpactWaterAvailability,
  EnvironmentalImpactWaterEstimate,
  EnvironmentalImpactUsageProfileEstimate,
  EnvironmentalImpactUsageProfileInput,
  EnvironmentalImpactPostDefinition,
  EnvironmentalImpactPostEstimate,
  EnvironmentalImpactPostKey,
  EnvironmentalImpactProjectSignal,
  EnvironmentalImpactProjectSignals,
  EnvironmentalImpactSnapshotRecord,
  EnvironmentalImpactScopeCurvePoint,
  EnvironmentalImpactScopeEstimate,
  EnvironmentalImpactScopeInput,
  EnvironmentalImpactScopeKey,
  EnvironmentalImpactScopeStatus,
  EnvironmentalImpactValidationIssue,
  EnvironmentalImpactValidationState,
} from "./types";
export {
  buildEnvironmentalImpactEstimatorMethodology,
  computeEnvironmentalImpactEstimate,
} from "./service";
export { buildElectricityEstimate, calculateElectricityCo2e } from "./services/electricity";
export { buildWaterEstimate, calculateIndirectElectricityWater } from "./services/water";
export {
  buildCodexInfrastructureUsageInput,
  buildCodexMonthlyUsageEstimate,
  buildCodexUsageWeeklySnapshot,
  getCodexUsageWeeklySnapshot,
  listCodexUsageWeeklySnapshots,
  upsertCodexUsageWeeklySnapshot,
} from "./codex-usage-store";
export {
  buildEnvironmentalImpactProjectSignals,
  loadEnvironmentalImpactProjectSignals,
} from "./project-signals";
export {
  normalizeEnvironmentalImpactEstimateInput,
} from "./validation";
