import type { WasteCategoryDefinition, WasteCategorySlug } from "./types";

const text = (fr: string, en: string) => ({ fr, en });

export const WASTE_CATEGORY_DEFINITIONS: Readonly<Record<WasteCategorySlug, WasteCategoryDefinition>> = {
  cigarette_butt: {
    slug: "cigarette_butt",
    family: "nicotine",
    labels: text("Mégot de cigarette", "Cigarette butt"),
    examples: [text("Mégot avec filtre", "Filtered cigarette butt"), text("Mégot roulé", "Hand-rolled cigarette butt")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "cigarette_waste",
    ppe: [text("Gants jetables ou réutilisables adaptés", "Suitable disposable or reusable gloves"), text("Pince si le sol est souillé", "Tongs when the ground is contaminated")],
    fieldInstructions: [text("Garder les mégots séparés des matières recyclables.", "Keep cigarette butts separate from recyclable materials."), text("Se laver les mains après la collecte.", "Wash hands after collection.")],
    prohibitions: [text("Ne pas ramasser à mains nues.", "Do not pick up with bare hands."), text("Ne pas les mettre dans le bac verre ou emballages.", "Do not put them in glass or packaging recycling.")],
    pedagogicalTags: ["nicotine", "collecte-securisee", "filiere-dediee"],
  },
  nicotine_pouch: {
    slug: "nicotine_pouch",
    family: "nicotine",
    labels: text("Sachet de nicotine", "Nicotine pouch"),
    examples: [text("Sachet de nicotine usagé", "Used nicotine pouch"), text("Pochette de tabac oral", "Oral tobacco pouch")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "residual_waste",
    ppe: [text("Gants adaptés", "Suitable gloves")],
    fieldInstructions: [text("Isoler les sachets dans un sac fermé et suivre la consigne locale.", "Place pouches in a closed bag and follow local guidance.")],
    prohibitions: [text("Ne pas les mélanger aux biodéchets ou au recyclage.", "Do not mix them with organic waste or recycling.")],
    pedagogicalTags: ["nicotine", "dechet-residuel", "consigne-locale"],
  },
  plastic: {
    slug: "plastic",
    family: "packaging",
    labels: text("Plastique", "Plastic"),
    examples: [text("Bouteille et emballage plastique", "Plastic bottle and packaging"), text("Film ou barquette", "Film or tray")],
    hazardLevel: "low",
    pickupPolicy: "basic_ppe_ok",
    disposalRoute: "municipal_recycling",
    ppe: [text("Gants de collecte", "Collection gloves")],
    fieldInstructions: [text("Vider si possible et séparer les éléments manifestement recyclables.", "Empty when possible and separate clearly recyclable items.")],
    prohibitions: [text("Ne pas supposer que tout plastique suit la même filière.", "Do not assume every plastic follows the same route.")],
    pedagogicalTags: ["tri", "emballage", "consigne-locale"],
  },
  glass: {
    slug: "glass",
    family: "glass",
    labels: text("Verre", "Glass"),
    examples: [text("Bouteille en verre", "Glass bottle"), text("Bocal en verre", "Glass jar")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "glass_container",
    ppe: [text("Gants résistants", "Cut-resistant gloves")],
    fieldInstructions: [text("Manipuler sans forcer et déposer dans la filière verre locale.", "Handle without force and use the local glass route.")],
    prohibitions: [text("Ne pas confondre verre d'emballage et vaisselle, miroir ou céramique.", "Do not confuse container glass with tableware, mirrors or ceramics.")],
    pedagogicalTags: ["tri", "verre", "filiere-locale"],
  },
  broken_glass: {
    slug: "broken_glass",
    family: "glass",
    labels: text("Verre cassé", "Broken glass"),
    examples: [text("Éclats de bouteille", "Bottle shards"), text("Morceaux de vitre", "Window glass fragments")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "local_authority_route",
    ppe: [text("Gants anti-coupure et contenant rigide adapté", "Cut-resistant gloves and a suitable rigid container")],
    fieldInstructions: [text("Balisser ou signaler la zone si la collecte n'est pas sûre.", "Mark or report the area when collection is unsafe."), text("Utiliser un contenant rigide fermé et suivre la consigne locale.", "Use a closed rigid container and follow local guidance.")],
    prohibitions: [text("Ne pas ramasser à mains nues.", "Do not pick up with bare hands."), text("Ne pas déposer les éclats directement dans un sac souple.", "Do not place shards directly in a soft bag.")],
    pedagogicalTags: ["securite", "coupant", "signalement"],
  },
  metal: {
    slug: "metal",
    family: "metal",
    labels: text("Métal", "Metal"),
    examples: [text("Canette", "Can"), text("Boîte ou pièce métallique", "Metal tin or piece")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "municipal_recycling",
    ppe: [text("Gants de collecte", "Collection gloves")],
    fieldInstructions: [text("Vérifier l'absence de bord tranchant avant manipulation.", "Check for sharp edges before handling.")],
    prohibitions: [text("Ne pas forcer sur un objet sous tension, pressurisé ou inconnu.", "Do not force an energized, pressurized or unknown object.")],
    pedagogicalTags: ["tri", "metal", "securite"],
  },
  mixed_residual: {
    slug: "mixed_residual",
    family: "residual",
    labels: text("Déchet résiduel mélangé", "Mixed residual waste"),
    examples: [text("Déchet souillé non identifiable", "Unidentifiable contaminated waste"), text("Mélange de petites matières", "Mixed small materials")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "residual_waste",
    ppe: [text("Gants de collecte", "Collection gloves")],
    fieldInstructions: [text("Ne trier que ce qui peut l'être sans risque et avec certitude.", "Only sort what can be identified safely and confidently.")],
    prohibitions: [text("Ne pas ouvrir un sac fermé ni manipuler un contenu inconnu.", "Do not open a closed bag or handle unknown contents.")],
    pedagogicalTags: ["dechet-residuel", "tri-prudent", "securite"],
  },
  bulky_furniture: {
    slug: "bulky_furniture",
    family: "bulky",
    labels: text("Encombrant et mobilier", "Bulky furniture"),
    examples: [text("Chaise, meuble ou matelas", "Chair, furniture or mattress"), text("Canapé", "Sofa")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "bulky_collection",
    ppe: [text("Gants et chaussures fermées", "Gloves and closed shoes")],
    fieldInstructions: [text("Organiser un enlèvement adapté ou demander de l'aide pour le portage.", "Arrange suitable collection or ask for help with lifting.")],
    prohibitions: [text("Ne pas soulever seul une charge lourde ou instable.", "Do not lift a heavy or unstable load alone.")],
    pedagogicalTags: ["encombrant", "logistique", "reemploi"],
  },
  wood: {
    slug: "wood",
    family: "wood",
    labels: text("Bois", "Wood"),
    examples: [text("Planche ou palette", "Board or pallet"), text("Branche ou élément de mobilier", "Branch or furniture part")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "wood_collection",
    ppe: [text("Gants et chaussures fermées", "Gloves and closed shoes")],
    fieldInstructions: [text("Repérer les clous, vis et échardes avant la manutention.", "Check for nails, screws and splinters before handling.")],
    prohibitions: [text("Ne pas brûler un bois traité ou d'origine inconnue.", "Do not burn treated or unknown wood.")],
    pedagogicalTags: ["bois", "securite", "reemploi"],
  },
  electrical_equipment: {
    slug: "electrical_equipment",
    family: "electrical",
    labels: text("Équipement électrique", "Electrical equipment"),
    examples: [text("Petit appareil électrique", "Small electrical appliance"), text("Écran ou câble", "Screen or cable")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "e_waste_collection",
    ppe: [text("Gants adaptés et absence de mise sous tension", "Suitable gloves and confirmed power isolation")],
    fieldInstructions: [text("Isoler l'appareil et retirer les piles seulement si c'est sûr.", "Isolate the equipment and remove batteries only when safe.")],
    prohibitions: [text("Ne pas démonter un appareil inconnu ni le remettre sous tension.", "Do not dismantle unknown equipment or power it on.")],
    pedagogicalTags: ["deee", "securite", "filiere-dediee"],
  },
  battery: {
    slug: "battery",
    family: "hazardous",
    labels: text("Pile et batterie", "Battery"),
    examples: [text("Pile bouton", "Button cell"), text("Batterie rechargeable", "Rechargeable battery")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "battery_dropoff",
    ppe: [text("Gants adaptés et contenant non conducteur si nécessaire", "Suitable gloves and a non-conductive container when needed")],
    fieldInstructions: [text("Isoler les bornes selon la consigne de la filière et déposer en point dédié.", "Isolate terminals according to the route guidance and use a dedicated drop-off point.")],
    prohibitions: [text("Ne pas percer, écraser, brûler ou mélanger une batterie endommagée.", "Do not puncture, crush, burn or mix a damaged battery.")],
    pedagogicalTags: ["pile", "danger-potentiel", "filiere-dediee"],
  },
  medicine: {
    slug: "medicine",
    family: "hazardous",
    labels: text("Médicament non utilisé ou contenant encore un produit", "Unused medicine or packaging that still contains medicine"),
    examples: [text("Médicament non utilisé ou périmé avec son contenu", "Unused or expired medicine with its contents"), text("Boîte, blister ou flacon contenant encore un médicament", "Box, blister or bottle that still contains medicine")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "pharmacy_takeback",
    ppe: [text("Gants adaptés pour un emballage souillé", "Suitable gloves for contaminated packaging")],
    fieldInstructions: [text("Pour un médicament non utilisé ou contenant encore un produit, orienter vers la pharmacie / Cyclamed. Un emballage totalement vide suit la consigne locale de tri selon sa matière.", "For unused medicine or packaging that still contains medicine, use a pharmacy / Cyclamed route. Totally empty packaging follows local sorting guidance for its material.")],
    prohibitions: [text("Ne pas ouvrir, consommer ou vider un produit trouvé.", "Do not open, consume or empty a found product."), text("Ne pas envoyer automatiquement une boîte, un blister ou un flacon totalement vide en pharmacie : vérifier sa matière et la consigne locale.", "Do not automatically take a totally empty box, blister or bottle to a pharmacy: check its material and local guidance."), text("Ne pas jeter un médicament dans l'évier ou les toilettes.", "Do not flush medicine down a sink or toilet.")],
    pedagogicalTags: ["medicament", "danger-potentiel", "filiere-dediee"],
  },
  sharps: {
    slug: "sharps",
    family: "hazardous",
    labels: text("Seringue ou aiguille à risque", "Risky syringe or needle"),
    examples: [text("Seringue avec aiguille", "Syringe with needle"), text("Aiguille de dispositif médical", "Needle from a medical device")],
    hazardLevel: "critical",
    pickupPolicy: "no_pickup",
    disposalRoute: "sharps_collection",
    ppe: [text("Équipement et formation adaptés uniquement", "Appropriate equipment and training only")],
    fieldInstructions: [text("Ne pas ramasser une seringue ou une aiguille trouvée sur le terrain : sécuriser la zone et signaler au service local ou habilité approprié.", "Do not pick up a syringe or needle found in the field: secure the area and report it to the appropriate local or authorized service.")],
    prohibitions: [text("Ne pas toucher, recapuchonner ou mettre dans un sac ordinaire.", "Do not touch, recap or place in an ordinary bag."), text("Ne pas assimiler une lame ou un objet coupant générique à cette catégorie de DASRI perforants.", "Do not treat a generic blade or sharp object as this category of sharps healthcare waste.")],
    pedagogicalTags: ["securite", "piquant", "signalement", "service-habilite", "dasri-perimetre"],
  },
  other: {
    slug: "other",
    family: "unknown",
    labels: text("Autre déchet", "Other waste"),
    examples: [text("Déchet non couvert par le référentiel", "Waste not covered by the reference"), text("Lame, cutter ou objet coupant non médical", "Non-medical blade, cutter or sharp object")],
    hazardLevel: "unknown",
    pickupPolicy: "no_pickup",
    disposalRoute: "local_authority_route",
    ppe: [text("Gants adaptés si la collecte est explicitement sûre", "Suitable gloves only when collection is explicitly safe")],
    fieldInstructions: [text("Décrire, isoler et demander la consigne locale avant toute collecte.", "Describe, isolate and ask for local guidance before collection.")],
    prohibitions: [text("Ne pas improviser une filière ou une manipulation.", "Do not improvise a route or handling method.")],
    pedagogicalTags: ["inconnu", "consigne-locale", "securite"],
  },
};

export const WASTE_CATEGORY_SLUGS = Object.keys(WASTE_CATEGORY_DEFINITIONS) as WasteCategorySlug[];

export function getWasteCategory(slug: WasteCategorySlug): WasteCategoryDefinition {
  return WASTE_CATEGORY_DEFINITIONS[slug];
}

export function isWasteCategorySlug(value: string): value is WasteCategorySlug {
  return value in WASTE_CATEGORY_DEFINITIONS;
}
