import type { WasteCategoryDefinition, WasteCategorySlug } from "./types";

const text = (fr: string, en: string) => ({ fr, en });

export const WASTE_CATEGORY_DEFINITIONS: Readonly<Record<WasteCategorySlug, WasteCategoryDefinition>> = {
  cigarette_butt: {
    slug: "cigarette_butt",
    family: "nicotine",
    labels: text("Mégot de cigarette", "Cigarette butt"),
    examples: [text("Mégot avec filtre", "Filtered cigarette butt"), text("Mégot roulé", "Hand-rolled cigarette butt")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "cigarette_waste",
    ppe: [text("Gants jetables ou réutilisables adaptés", "Suitable disposable or reusable gloves"), text("Pince si le sol est souillé", "Tongs when the ground is contaminated")],
    fieldInstructions: [text("Garder les mégots séparés des matières recyclables.", "Keep cigarette butts separate from recyclable materials."), text("Se laver les mains après la collecte.", "Wash hands after collection.")],
    prohibitions: [text("Ne pas ramasser à mains nues.", "Do not pick up with bare hands."), text("Ne pas les mettre dans le bac verre ou emballages.", "Do not put them in glass or packaging recycling.")],
    pedagogicalTags: ["nicotine", "collecte-securisee", "filiere-dediee"],
  },
  nicotine_pouch: {
    slug: "nicotine_pouch",
    family: "nicotine",
    labels: text("Sachet de nicotine", "Nicotine pouch"),
    examples: [text("Sachet de nicotine usagé", "Used nicotine pouch"), text("Pochette de tabac oral", "Oral tobacco pouch")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "residual_waste",
    ppe: [text("Gants adaptés", "Suitable gloves")],
    fieldInstructions: [text("Isoler les sachets dans un sac fermé et suivre la consigne locale.", "Place pouches in a closed bag and follow local guidance.")],
    prohibitions: [text("Ne pas les mélanger aux biodéchets ou au recyclage.", "Do not mix them with organic waste or recycling.")],
    pedagogicalTags: ["nicotine", "dechet-residuel", "consigne-locale"],
  },
  plastic: {
    slug: "plastic",
    family: "packaging",
    labels: text("Plastique", "Plastic"),
    examples: [text("Bouteille et emballage plastique", "Plastic bottle and packaging"), text("Film ou barquette", "Film or tray")],
    hazardLevel: "low",
    pickupPolicy: "basic_ppe_ok",
    disposalRoute: "municipal_recycling",
    ppe: [text("Gants de collecte", "Collection gloves")],
    fieldInstructions: [text("Vider si possible et séparer les éléments manifestement recyclables.", "Empty when possible and separate clearly recyclable items.")],
    prohibitions: [text("Ne pas supposer que tout plastique suit la même filière.", "Do not assume every plastic follows the same route.")],
    pedagogicalTags: ["tri", "emballage", "consigne-locale"],
  },
  glass: {
    slug: "glass",
    family: "glass",
    labels: text("Verre", "Glass"),
    examples: [text("Bouteille en verre", "Glass bottle"), text("Bocal en verre", "Glass jar")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "glass_container",
    ppe: [text("Gants résistants", "Cut-resistant gloves")],
    fieldInstructions: [text("Manipuler sans forcer et déposer dans la filière verre locale.", "Handle without force and use the local glass route.")],
    prohibitions: [text("Ne pas confondre verre d'emballage et vaisselle, miroir ou céramique.", "Do not confuse container glass with tableware, mirrors or ceramics.")],
    pedagogicalTags: ["tri", "verre", "filiere-locale"],
  },
  broken_glass: {
    slug: "broken_glass",
    family: "glass",
    labels: text("Verre cassé", "Broken glass"),
    examples: [text("Éclats de bouteille", "Bottle shards"), text("Morceaux de vitre", "Window glass fragments")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "local_authority_route",
    ppe: [text("Gants anti-coupure et contenant rigide adapté", "Cut-resistant gloves and a suitable rigid container")],
    fieldInstructions: [text("Balisser ou signaler la zone si la collecte n'est pas sûre.", "Mark or report the area when collection is unsafe."), text("Utiliser un contenant rigide fermé et suivre la consigne locale.", "Use a closed rigid container and follow local guidance.")],
    prohibitions: [text("Ne pas ramasser à mains nues.", "Do not pick up with bare hands."), text("Ne pas déposer les éclats directement dans un sac souple.", "Do not place shards directly in a soft bag.")],
    pedagogicalTags: ["securite", "coupant", "signalement"],
  },
  metal: {
    slug: "metal",
    family: "metal",
    labels: text("Métal", "Metal"),
    examples: [text("Canette", "Can"), text("Boîte ou pièce métallique", "Metal tin or piece")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "municipal_recycling",
    ppe: [text("Gants de collecte", "Collection gloves")],
    fieldInstructions: [text("Vérifier l'absence de bord tranchant avant manipulation.", "Check for sharp edges before handling.")],
    prohibitions: [text("Ne pas forcer sur un objet sous tension, pressurisé ou inconnu.", "Do not force an energized, pressurized or unknown object.")],
    pedagogicalTags: ["tri", "metal", "securite"],
  },
  mixed_residual: {
    slug: "mixed_residual",
    family: "residual",
    labels: text("Déchet résiduel mélangé", "Mixed residual waste"),
    examples: [text("Déchet souillé non identifiable", "Unidentifiable contaminated waste"), text("Mélange de petites matières", "Mixed small materials")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "residual_waste",
    ppe: [text("Gants de collecte", "Collection gloves")],
    fieldInstructions: [text("Ne trier que ce qui peut l'être sans risque et avec certitude.", "Only sort what can be identified safely and confidently.")],
    prohibitions: [text("Ne pas ouvrir un sac fermé ni manipuler un contenu inconnu.", "Do not open a closed bag or handle unknown contents.")],
    pedagogicalTags: ["dechet-residuel", "tri-prudent", "securite"],
  },
  bulky_furniture: {
    slug: "bulky_furniture",
    family: "bulky",
    labels: text("Encombrant et mobilier", "Bulky furniture"),
    examples: [text("Chaise, meuble ou matelas", "Chair, furniture or mattress"), text("Canapé", "Sofa")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "bulky_collection",
    ppe: [text("Gants et chaussures fermées", "Gloves and closed shoes")],
    fieldInstructions: [text("Organiser un enlèvement adapté ou demander de l'aide pour le portage.", "Arrange suitable collection or ask for help with lifting.")],
    prohibitions: [text("Ne pas soulever seul une charge lourde ou instable.", "Do not lift a heavy or unstable load alone.")],
    pedagogicalTags: ["encombrant", "logistique", "reemploi"],
  },
  wood: {
    slug: "wood",
    family: "wood",
    labels: text("Bois", "Wood"),
    examples: [text("Planche ou palette", "Board or pallet"), text("Branche ou élément de mobilier", "Branch or furniture part")],
    hazardLevel: "caution",
    pickupPolicy: "basic_ppe_with_care",
    disposalRoute: "wood_collection",
    ppe: [text("Gants et chaussures fermées", "Gloves and closed shoes")],
    fieldInstructions: [text("Repérer les clous, vis et échardes avant la manutention.", "Check for nails, screws and splinters before handling.")],
    prohibitions: [text("Ne pas brûler un bois traité ou d'origine inconnue.", "Do not burn treated or unknown wood.")],
    pedagogicalTags: ["bois", "securite", "reemploi"],
  },
  electrical_equipment: {
    slug: "electrical_equipment",
    family: "electrical",
    labels: text("Équipement électrique", "Electrical equipment"),
    examples: [text("Petit appareil électrique", "Small electrical appliance"), text("Écran ou câble", "Screen or cable")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "e_waste_collection",
    ppe: [text("Gants adaptés et absence de mise sous tension", "Suitable gloves and confirmed power isolation")],
    fieldInstructions: [text("Isoler l'appareil et retirer les piles seulement si c'est sûr.", "Isolate the equipment and remove batteries only when safe.")],
    prohibitions: [text("Ne pas démonter un appareil inconnu ni le remettre sous tension.", "Do not dismantle unknown equipment or power it on.")],
    pedagogicalTags: ["deee", "securite", "filiere-dediee"],
  },
  battery: {
    slug: "battery",
    family: "hazardous",
    labels: text("Pile et batterie", "Battery"),
    examples: [text("Pile bouton", "Button cell"), text("Batterie rechargeable", "Rechargeable battery")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "battery_dropoff",
    ppe: [text("Gants adaptés et contenant non conducteur si nécessaire", "Suitable gloves and a non-conductive container when needed")],
    fieldInstructions: [text("Isoler les bornes selon la consigne de la filière et déposer en point dédié.", "Isolate terminals according to the route guidance and use a dedicated drop-off point.")],
    prohibitions: [text("Ne pas percer, écraser, brûler ou mélanger une batterie endommagée.", "Do not puncture, crush, burn or mix a damaged battery.")],
    pedagogicalTags: ["pile", "danger-potentiel", "filiere-dediee"],
  },
  medicine: {
    slug: "medicine",
    family: "hazardous",
    labels: text("Médicament", "Medicine"),
    examples: [text("Boîte ou blister de médicament", "Medicine box or blister"), text("Flacon de médicament", "Medicine bottle")],
    hazardLevel: "high",
    pickupPolicy: "trained_only",
    disposalRoute: "pharmacy_takeback",
    ppe: [text("Gants adaptés pour un emballage souillé", "Suitable gloves for contaminated packaging")],
    fieldInstructions: [text("Orienter vers la pharmacie ou la filière locale prévue.", "Use the pharmacy or designated local route.")],
    prohibitions: [text("Ne pas ouvrir, consommer ou vider un produit trouvé.", "Do not open, consume or empty a found product."), text("Ne pas jeter dans l'évier ou les toilettes.", "Do not flush it down a sink or toilet.")],
    pedagogicalTags: ["medicament", "danger-potentiel", "filiere-dediee"],
  },
  sharps: {
    slug: "sharps",
    family: "hazardous",
    labels: text("Objet piquant ou coupant", "Sharps"),
    examples: [text("Aiguille ou seringue", "Needle or syringe"), text("Lame ou objet coupant", "Blade or sharp object")],
    hazardLevel: "critical",
    pickupPolicy: "no_pickup",
    disposalRoute: "sharps_collection",
    ppe: [text("Équipement et formation adaptés uniquement", "Appropriate equipment and training only")],
    fieldInstructions: [text("Sécuriser la zone et utiliser un signalement ou un service habilité.", "Secure the area and use a report or an authorized service.")],
    prohibitions: [text("Ne pas toucher, recapuchonner ou mettre dans un sac ordinaire.", "Do not touch, recap or place in an ordinary bag.")],
    pedagogicalTags: ["securite", "piquant", "signalement", "service-habilite"],
  },
  other: {
    slug: "other",
    family: "unknown",
    labels: text("Autre déchet", "Other waste"),
    examples: [text("Déchet non couvert par le référentiel", "Waste not covered by the reference")],
    hazardLevel: "unknown",
    pickupPolicy: "no_pickup",
    disposalRoute: "local_authority_route",
    ppe: [text("Gants adaptés si la collecte est explicitement sûre", "Suitable gloves only when collection is explicitly safe")],
    fieldInstructions: [text("Décrire, isoler et demander la consigne locale avant toute collecte.", "Describe, isolate and ask for local guidance before collection.")],
    prohibitions: [text("Ne pas improviser une filière ou une manipulation.", "Do not improvise a route or handling method.")],
    pedagogicalTags: ["inconnu", "consigne-locale", "securite"],
  },
};

export const WASTE_CATEGORY_SLUGS = Object.keys(WASTE_CATEGORY_DEFINITIONS) as WasteCategorySlug[];

export function getWasteCategory(slug: WasteCategorySlug): WasteCategoryDefinition {
  return WASTE_CATEGORY_DEFINITIONS[slug];
}

export function isWasteCategorySlug(value: string): value is WasteCategorySlug {
  return value in WASTE_CATEGORY_DEFINITIONS;
}
