import { ACTION_PREPARATION_CHECKLIST_DEFAULTS } from "@/lib/actions/preparation-contract";
import type { ActionDuplicatePrefill } from "@/lib/actions/action-duplication";
import type { FormState } from "../model";

export function applyDuplicatePrefillToForm(form: FormState, prefill: ActionDuplicatePrefill): FormState {
  return {
    ...form,
    actionTitle: prefill.title,
    shortDescription: prefill.shortDescription,
    locationLabel: prefill.locationLabel,
    communeZoneLabel: prefill.communeZoneLabel,
    departureLocationLabel: prefill.departureLocationLabel,
    midRouteLocationLabel: prefill.midRouteLocationLabel,
    arrivalLocationLabel: prefill.arrivalLocationLabel,
    latitude: prefill.latitude === null ? "" : String(prefill.latitude),
    longitude: prefill.longitude === null ? "" : String(prefill.longitude),
    arrivalCoordinates: prefill.arrivalCoordinates,
    midRouteCoordinates: prefill.midRouteCoordinates,
    interventionMode: prefill.interventionMode ?? form.interventionMode,
    routeTopology: prefill.routeTopology ?? "loop",
    routeTargetDistanceKm: prefill.routeTargetDistanceKm === null ? "" : String(prefill.routeTargetDistanceKm),
    routeTargetDistanceKmManuallySet: prefill.routeTargetDistanceSource === "manual",
    plannedObjective: prefill.plannedObjective ?? "",
    placeType: prefill.placeType,
    estimatedDifficulty: prefill.estimatedDifficulty ?? "",
    accessibility: prefill.accessibility,
    accessibilityStatus: prefill.accessibilityStatus ?? "not_evaluated",
    formalitiesContext: null,
    safetyInstructions: prefill.safetyInstructions,
    recommendedMaterials: prefill.recommendedMaterials,
    materialsProvided: prefill.materialsProvided,
    suggestedMaterials: [...prefill.suggestedMaterials],
    participantMessage: prefill.participantMessage,
    logisticsNotes: prefill.logisticsNotes,
    preparationChecklist: ACTION_PREPARATION_CHECKLIST_DEFAULTS.map((item) => ({ ...item })),
    checklistBeforeDeparture: "",
    organizerType: prefill.organizerType ?? "",
    organizerId: prefill.organizerId,
    organizerName: prefill.organizerName,
    associationName: prefill.associationName || form.associationName,
    organizerAccounts: "",
    participantAccounts: [],
    groupJoinEnabled: false,
    wasteCategories: [...prefill.expectedWasteCategories],
    actionDate: "",
    meetingTime: "",
    departureTime: "",
    eventStartTime: "",
    eventEndTime: "",
    durationMinutes: "",
    volunteersCount: "",
    childrenCount: "",
    adultCount: "",
    retiredCount: "",
    operationalRoute: prefill.operationalRoute,
    routeCalibrationContext: prefill.routeCalibrationContext,
    plannerProof: null,
    gpxImport: null,
  };
}
