import type { RubriqueCategory, RubriqueDefinition } from "./types";
import {
  ADMIN_GODMODE_ROUTE,
  ADMIN_ROUTE,
  DASHBOARD_ROUTE,
  EXPLORER_ROUTE,
  PILOTAGE_ROUTE,
  PROFIL_ROUTE,
  SPONSOR_PORTAL_ROUTE,
} from "@/lib/accueil-pilotage-routes";

export const RUBRIQUE_CATEGORIES = [
  { id: "pilotage", label: { fr: "Accueil & Pilotage", en: "Home & Operations" } },
  { id: "terrain", label: { fr: "Actions Terrain", en: "Field actions" } },
  {
    id: "analysis",
    label: { fr: "Analyse & Contexte", en: "Analysis & Context" },
  },
  { id: "resources", label: { fr: "Guide & Outils", en: "Guide & Tools" } },
  { id: "community", label: { fr: "Communauté", en: "Community" } },
] as const satisfies readonly RubriqueCategory[];

export const RUBRIQUE_REGISTRY = [
  {
    id: "profile",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 20,
    kind: "app-route",
    route: PROFIL_ROUTE,
    label: { fr: "Profil", en: "Profile" },
    description: { fr: "Alias du tableau de bord personnel", en: "Personal dashboard alias" },
    availability: "hidden",
    implementation: "finalized",
  },
  {
    id: "explorer",
    categoryId: "resources",
    spaceId: "decide",
    priority: 18,
    kind: "app-route",
    route: EXPLORER_ROUTE,
    label: { fr: "Sommaire", en: "Summary" },
    description: {
      fr: "Plan du site et accès direct à toutes les rubriques",
      en: "Site map and direct access to all sections",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "dashboard",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 10,
    kind: "app-route",
    route: DASHBOARD_ROUTE,
    label: { fr: "Mon espace", en: "Dashboard" },
    description: { fr: "Vue d'ensemble, profil et pilotage", en: "Overview, profile and monitoring" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "reports",
    categoryId: "analysis",
    spaceId: "decide",
    priority: 30,
    kind: "app-route",
    route: "/reports",
    label: { fr: "Rapports d'impact", en: "Impact reports" },
    description: {
      fr: "Analysez vos résultats et exportez vos données",
      en: "Analyze your results and export your data",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "methodologie",
    categoryId: "analysis",
    spaceId: "decide",
    priority: 32,
    kind: "app-route",
    route: "/methodologie",
    label: { fr: "Méthodologie", en: "Methodology" },
    description: {
      fr: "Comprenez les calculs et les règles d'impact",
      en: "Understand the calculations and impact rules",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "admin",
    categoryId: "pilotage",
    spaceId: "supervise",
    priority: 10,
    kind: "app-route",
    route: ADMIN_ROUTE,
    label: { fr: "Administration", en: "Administration" },
    description: {
      fr: "Back-office technique, modération et supervision",
      en: "Technical back office, moderation and supervision",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "pilotage",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 14,
    kind: "app-route",
    route: PILOTAGE_ROUTE,
    label: { fr: "Pilotage", en: "Operations" },
    description: {
      fr: "Arbitrages transverses et cockpit opérationnel",
      en: "Strategic cockpit and operational arbitration",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "elus",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 40,
    kind: "section",
    route: "/sections/elus",
    label: { fr: "Gouvernance", en: "Governance" },
    description: {
      fr: "Coordination publique et résultats territoriaux",
      en: "Public coordination and territorial results",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "new",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 10,
    kind: "app-route",
    route: "/actions/new",
    label: { fr: "Déclarer une action", en: "Declare action" },
    description: { fr: "Signalez une zone ou validez un nettoyage", en: "Report a hotspot or validate a cleanup" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "rejoindre-un-formulaire",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 12,
    kind: "section",
    route: "/sections/rejoindre-un-formulaire",
    label: { fr: "Rejoindre un formulaire", en: "Join a form" },
    description: {
      fr: "Architecture de départ pour rejoindre une action de groupe",
      en: "Starting architecture for joining a group action",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "map",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 20,
    kind: "app-route",
    route: "/actions/map",
    label: { fr: "Carte des actions", en: "Map" },
    description: { fr: "Vue géolocalisée de l'engagement", en: "Geo view" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "history",
    categoryId: "terrain",
    spaceId: "supervise",
    priority: 20,
    kind: "app-route",
    route: "/actions/history",
    label: { fr: "Historique", en: "History" },
    description: { fr: "Toutes vos actions passées", en: "All past actions" },
    availability: "hidden",
    implementation: "finalized",
  },
  {
    id: "route",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 30,
    kind: "section",
    route: "/sections/route",
    label: { fr: "Où agir ?", en: "Where to act?" },
    description: { fr: "Optimisez votre parcours selon l'impact", en: "Optimize your route based on impact" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "recycling",
    categoryId: "terrain",
    spaceId: "prepare",
    priority: 30,
    kind: "section",
    route: "/sections/recycling",
    label: { fr: "Guide du tri", en: "Recycling guide" },
    description: { fr: "Valorisation et seconde vie des déchets", en: "Waste reuse and valorization" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "compost",
    categoryId: "terrain",
    spaceId: "prepare",
    priority: 31,
    kind: "section",
    route: "/sections/compost",
    label: { fr: "Compostage", en: "Composting" },
    description: {
      fr: "Guide pour composter chez soi ou en quartier",
      en: "Guide to composting at home or locally",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "climate",
    categoryId: "analysis",
    spaceId: "decide",
    priority: 50,
    kind: "section",
    route: "/sections/climate",
    label: { fr: "Comprendre l'enjeu", en: "Climate context" },
    description: {
      fr: "Limites planétaires et sens de notre impact",
      en: "Planetary boundaries and the meaning of our impact",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "weather",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 25,
    kind: "section",
    route: "/sections/weather",
    label: { fr: "Organiser une action", en: "Organize an action" },
    description: {
      fr: "Consultez la météo réelle, préparez le terrain et organisez une cleanwalk efficace",
      en: "Check the real weather, prepare the field and organize an effective cleanwalk",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "community",
    categoryId: "community",
    spaceId: "execute",
    priority: 40,
    kind: "section",
    route: "/sections/community",
    label: { fr: "Communauté", en: "Community" },
    description: {
      fr: "Coordination de la communauté et accès au réseau de partenaires",
      en: "Community coordination and partner network access",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "feedback",
    categoryId: "community",
    spaceId: "decide",
    priority: 41,
    kind: "section",
    route: "/sections/feedback",
    label: { fr: "Idées et problèmes", en: "Ideas & issues" },
    description: {
      fr: "Partagez vos idées et signalez des problèmes",
      en: "Share ideas and report issues",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "gamification",
    categoryId: "community",
    spaceId: "decide",
    priority: 60,
    kind: "section",
    route: "/sections/gamification",
    label: { fr: "Progression et badges", en: "Your progress" },
    description: { fr: "Suivez votre évolution et vos succès", en: "Track your evolution and badges" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "actors",
    categoryId: "community",
    spaceId: "prepare",
    priority: 40,
    kind: "section",
    route: "/sections/actors",
    label: { fr: "Réseau engagé", en: "Partner network" },
    description: { fr: "Découvrez les structures mobilisées localement", en: "Discover locally engaged organizations" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "network",
    categoryId: "community",
    spaceId: "prepare",
    priority: 42,
    kind: "app-route",
    route: "/partners/network",
    label: { fr: "Communauté (alias partenaires)", en: "Community (partner alias)" },
    description: {
      fr: "Alias technique vers la page Communauté",
      en: "Technical alias to the Community page",
    },
    availability: "hidden",
    implementation: "finalized",
  },
  {
    id: "annuaire",
    categoryId: "community",
    spaceId: "prepare",
    priority: 45,
    kind: "section",
    route: "/sections/annuaire",
    label: { fr: "Annuaire des acteurs", en: "Directory" },
    description: {
      fr: "Trouvez les bons contacts dans votre zone",
      en: "Find the right contacts in your area",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "dm",
    categoryId: "community",
    spaceId: "execute",
    priority: 41,
    kind: "section",
    route: "/sections/dm",
    label: { fr: "Messages privés", en: "Messages" },
    description: {
      fr: "Échanges directs avec les membres du réseau",
      en: "Direct exchanges with network members",
    },
    availability: "hidden",
    implementation: "finalized",
  },
  {
    id: "messagerie",
    categoryId: "community",
    spaceId: "execute",
    priority: 42,
    kind: "section",
    route: "/sections/messagerie",
    label: { fr: "Groupes de discussion", en: "Discussion groups" },
    description: {
      fr: "Échanges collectifs thématiques et locaux",
      en: "Thematic and local group discussions",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "open-data",
    categoryId: "analysis",
    spaceId: "decide",
    priority: 47,
    kind: "section",
    route: "/sections/open-data",
    label: { fr: "Données publiques", en: "Open Data" },
    description: {
      fr: "Données publiques et exports pour la recherche",
      en: "Open data and research exports",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "funding",
    categoryId: "community",
    spaceId: "decide",
    priority: 48,
    kind: "section",
    route: "/sections/funding",
    label: { fr: "Soutenir le Projet", en: "Support Us" },
    description: {
      fr: "Mécénat écologique et parrainage de zones",
      en: "Eco-patronage and zone sponsorship",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "trash-spotter",
    categoryId: "community",
    spaceId: "supervise",
    priority: 50,
    kind: "section",
    route: "/sections/trash-spotter",
    label: { fr: "Signaler un déchet", en: "Trash Spotter" },
    description: { fr: "Localisez un nouveau hotspot de pollution", en: "Locate a new pollution hotspot" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-comprendre",
    categoryId: "analysis",
    spaceId: "prepare",
    priority: 6,
    kind: "app-route",
    route: "/learn/comprendre",
    label: { fr: "Vulgarisation", en: "Explanation" },
    description: {
      fr: "Repères scientifiques, contexte et vulgarisation",
      en: "Scientific context, cues and explanations",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-sentrainer",
    categoryId: "resources",
    spaceId: "prepare",
    priority: 7,
    kind: "app-route",
    route: "/learn/sentrainer",
    label: { fr: "S'entraîner", en: "Practice" },
    description: {
      fr: "Quiz et exercices pour tester vos connaissances",
      en: "Quizzes and exercises to test your knowledge",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-bonnes-pratiques",
    categoryId: "resources",
    spaceId: "prepare",
    priority: 8,
    kind: "app-route",
    route: "/learn/bonnes-pratiques",
    label: {
      fr: "Tri, composte, comportements",
      en: "Sorting, composting, behaviors",
    },
    description: {
      fr: "Repères de tri, compostage et conduite utile",
      en: "Sorting, composting and useful behavior cues",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "sponsor",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 35,
    kind: "app-route",
    route: SPONSOR_PORTAL_ROUTE,
    label: { fr: "Portail décideurs", en: "Sponsor portal" },
    description: { fr: "Analyse d'impact et pilotage territorial", en: "Impact analysis and territorial monitoring" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "godmode",
    categoryId: "pilotage",
    spaceId: "supervise",
    priority: 5,
    kind: "app-route",
    route: ADMIN_GODMODE_ROUTE,
    label: { fr: "Administration avancée", en: "Advanced administration" },
    description: {
      fr: "Sous-partie cachée de l'administration réservée au profil max",
      en: "Hidden administration sub-section reserved for the max profile",
    },
    availability: "hidden",
    implementation: "finalized",
  },
] as const satisfies readonly RubriqueDefinition[];
