import type { RubriqueCategory, RubriqueDefinition } from "./types";

export const RUBRIQUE_CATEGORIES = [
  { id: "pilotage", label: { fr: "Accueil & Pilotage", en: "Home & Operations" } },
  { id: "terrain", label: { fr: "Actions Terrain", en: "Field actions" } },
  {
    id: "analysis",
    label: { fr: "Analyse & Contexte", en: "Analysis & Context" },
  },
  { id: "resources", label: { fr: "Guide & Outils", en: "Guide & Tools" } },
  { id: "community", label: { fr: "Communauté", en: "Community" } },
] as const satisfies readonly RubriqueCategory[];

export const RUBRIQUE_REGISTRY = [
  {
    id: "profile",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 20,
    kind: "app-route",
    route: "/profil",
    label: { fr: "Profil", en: "Profile" },
    description: { fr: "Suivez vos actions et gérez votre compte", en: "Track your actions and manage your account" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "explorer",
    categoryId: "resources",
    spaceId: "decide",
    priority: 18,
    kind: "app-route",
    route: "/explorer",
    label: { fr: "Sommaire", en: "Summary" },
    description: {
      fr: "Plan du site et accès direct à toutes les rubriques",
      en: "Site map and direct access to all sections",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "dashboard",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 10,
    kind: "app-route",
    route: "/dashboard",
    label: { fr: "Tableau de bord", en: "Dashboard" },
    description: { fr: "Vue d'ensemble et pilotage", en: "Overview and monitoring" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "reports",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 30,
    kind: "app-route",
    route: "/reports",
    label: { fr: "Rapports d'impact", en: "Impact reports" },
    description: {
      fr: "Analysez vos résultats et exportez vos données",
      en: "Analyze your results and export your data",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "admin",
    categoryId: "pilotage",
    spaceId: "supervise",
    priority: 10,
    kind: "app-route",
    route: "/admin",
    label: { fr: "Administration", en: "Admin Space" },
    description: {
      fr: "Modération et supervision du réseau",
      en: "Network moderation and supervision",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "pilotage",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 14,
    kind: "app-route",
    route: "/pilotage",
    label: { fr: "Pilotage", en: "Operations" },
    description: {
      fr: "Arbitrages transverses et cockpit opérationnel",
      en: "Strategic cockpit and operational arbitration",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "elus",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 40,
    kind: "section",
    route: "/sections/elus",
    label: { fr: "Gouvernance", en: "Governance" },
    description: {
      fr: "Coordination publique et résultats territoriaux",
      en: "Public coordination and territorial results",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "new",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 10,
    kind: "app-route",
    route: "/actions/new",
    label: { fr: "Déclarer une action", en: "Declare action" },
    description: { fr: "Signalez une zone ou validez un nettoyage", en: "Report a hotspot or validate a cleanup" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "map",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 20,
    kind: "app-route",
    route: "/actions/map",
    label: { fr: "Carte des actions", en: "Map" },
    description: { fr: "Vue géolocalisée de l'engagement", en: "Geo view" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "sandbox",
    categoryId: "terrain",
    spaceId: "prepare",
    priority: 22,
    kind: "section",
    route: "/sections/sandbox",
    label: { fr: "Carte d'entraînement", en: "Training map" },
    description: {
      fr: "Testez les outils et filtres en toute sécurité",
      en: "Safely test tools and filters before starting",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "history",
    categoryId: "terrain",
    spaceId: "supervise",
    priority: 20,
    kind: "app-route",
    route: "/actions/history",
    label: { fr: "Historique", en: "History" },
    description: { fr: "Toutes vos actions passées", en: "All past actions" },
    availability: "hidden",
    implementation: "finalized",
  },
  {
    id: "route",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 30,
    kind: "section",
    route: "/sections/route",
    label: { fr: "Itinéraire prioritaire", en: "AI routing" },
    description: { fr: "Optimisez votre parcours selon l'impact", en: "Optimize your route based on impact" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "recycling",
    categoryId: "terrain",
    spaceId: "prepare",
    priority: 30,
    kind: "section",
    route: "/sections/recycling",
    label: { fr: "Guide du tri", en: "Recycling guide" },
    description: { fr: "Valorisation et seconde vie des déchets", en: "Waste reuse and valorization" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "compost",
    categoryId: "terrain",
    spaceId: "prepare",
    priority: 31,
    kind: "section",
    route: "/sections/compost",
    label: { fr: "Compostage", en: "Composting" },
    description: {
      fr: "Guide pour composter chez soi ou en quartier",
      en: "Guide to composting at home or locally",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "climate",
    categoryId: "analysis",
    spaceId: "decide",
    priority: 50,
    kind: "section",
    route: "/sections/climate",
    label: { fr: "Comprendre l'enjeu", en: "Climate context" },
    description: {
      fr: "Limites planétaires et sens de notre impact",
      en: "Planetary boundaries and the meaning of our impact",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "weather",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 25,
    kind: "section",
    route: "/sections/weather",
    label: { fr: "Météo terrain", en: "Field weather" },
    description: { fr: "Anticipez les conditions opérationnelles", en: "Anticipate operational conditions" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "guide",
    categoryId: "terrain",
    spaceId: "execute",
    priority: 26,
    kind: "section",
    route: "/sections/guide",
    label: { fr: "Mode d'emploi", en: "How to use" },
    description: { fr: "Bonnes pratiques et workflow de collecte", en: "Best practices and collection workflow" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "community",
    categoryId: "community",
    spaceId: "execute",
    priority: 40,
    kind: "section",
    route: "/sections/community",
    label: { fr: "Vie de la communauté", en: "Community life" },
    description: {
      fr: "Coordination des événements et rassemblements",
      en: "Event coordination and gatherings",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "feedback",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 41,
    kind: "section",
    route: "/sections/feedback",
    label: { fr: "Feedback", en: "Feedback" },
    description: {
      fr: "Partagez vos idées et signalez des problèmes",
      en: "Share ideas and report issues",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "gamification",
    categoryId: "community",
    spaceId: "decide",
    priority: 60,
    kind: "section",
    route: "/sections/gamification",
    label: { fr: "Progression et badges", en: "Your progress" },
    description: { fr: "Suivez votre évolution et vos succès", en: "Track your evolution and badges" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "actors",
    categoryId: "community",
    spaceId: "prepare",
    priority: 40,
    kind: "section",
    route: "/sections/actors",
    label: { fr: "Réseau engagé", en: "Partner network" },
    description: { fr: "Découvrez les structures mobilisées localement", en: "Discover locally engaged organizations" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "network",
    categoryId: "community",
    spaceId: "prepare",
    priority: 42,
    kind: "app-route",
    route: "/partners/network",
    label: { fr: "Cartographie des partenaires", en: "Partner map" },
    description: {
      fr: "Accédez aux fiches des partenaires actifs",
      en: "Access active partner profiles",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "annuaire",
    categoryId: "community",
    spaceId: "prepare",
    priority: 45,
    kind: "section",
    route: "/sections/annuaire",
    label: { fr: "Annuaire des acteurs", en: "Directory" },
    description: {
      fr: "Trouvez les bons contacts dans votre zone",
      en: "Find the right contacts in your area",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "dm",
    categoryId: "community",
    spaceId: "execute",
    priority: 41,
    kind: "section",
    route: "/sections/dm",
    label: { fr: "Messages Privés", en: "Messages" },
    description: {
      fr: "Échanges directs avec les membres du réseau",
      en: "Direct exchanges with network members",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "messagerie",
    categoryId: "community",
    spaceId: "execute",
    priority: 42,
    kind: "section",
    route: "/sections/messagerie",
    label: { fr: "Canaux de Discussion", en: "Discussion Channels" },
    description: {
      fr: "Échanges collectifs thématiques et locaux",
      en: "Thematic and local group discussions",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "open-data",
    categoryId: "community",
    spaceId: "decide",
    priority: 47,
    kind: "section",
    route: "/sections/open-data",
    label: { fr: "Observatoire Public", en: "Open Data" },
    description: {
      fr: "Données ouvertes et exports pour la recherche",
      en: "Open data and research exports",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "funding",
    categoryId: "community",
    spaceId: "decide",
    priority: 48,
    kind: "section",
    route: "/sections/funding",
    label: { fr: "Soutenir le Projet", en: "Support Us" },
    description: {
      fr: "Mécénat écologique et parrainage de zones",
      en: "Eco-patronage and zone sponsorship",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "trash-spotter",
    categoryId: "community",
    spaceId: "supervise",
    priority: 50,
    kind: "section",
    route: "/sections/trash-spotter",
    label: { fr: "Signalement de déchets", en: "Trash spotting" },
    description: { fr: "Localisez un nouveau hotspot de pollution", en: "Locate a new pollution hotspot" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "hub",
    categoryId: "resources",
    spaceId: "prepare",
    priority: 5,
    kind: "app-route",
    route: "/learn/hub",
    label: { fr: "Hub éducatif", en: "Learning hub" },
    description: {
      fr: "Apprenez, entraînez-vous et adoptez les bons gestes",
      en: "Learn, practice and adopt best habits",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-comprendre",
    categoryId: "analysis",
    spaceId: "prepare",
    priority: 6,
    kind: "app-route",
    route: "/learn/comprendre",
    label: { fr: "Comprendre l'enjeu", en: "Understand" },
    description: {
      fr: "Repères scientifiques et ordres de grandeur",
      en: "Scientific data and orders of magnitude",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-sentrainer",
    categoryId: "resources",
    spaceId: "prepare",
    priority: 7,
    kind: "app-route",
    route: "/learn/sentrainer",
    label: { fr: "S'entraîner", en: "Practice" },
    description: {
      fr: "Quiz et exercices pour tester vos connaissances",
      en: "Quizzes and exercises to test your knowledge",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-bonnes-pratiques",
    categoryId: "resources",
    spaceId: "prepare",
    priority: 8,
    kind: "app-route",
    route: "/learn/bonnes-pratiques",
    label: { fr: "Bonnes pratiques", en: "Best practices" },
    description: {
      fr: "Gestes utiles et guides pratiques",
      en: "Useful gestures and practical guides",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "learn-ressources",
    categoryId: "resources",
    spaceId: "prepare",
    priority: 9,
    kind: "app-route",
    route: "/learn/ressources",
    label: { fr: "Ressources et kits", en: "Resources and kits" },
    description: {
      fr: "Outils, kits terrain et repères utiles",
      en: "Tools, field kits and useful references",
    },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "sponsor",
    categoryId: "pilotage",
    spaceId: "decide",
    priority: 35,
    kind: "app-route",
    route: "/sponsor-portal",
    label: { fr: "Espace décideur", en: "Sponsor portal" },
    description: { fr: "Analyse d'impact et pilotage territorial", en: "Impact analysis and territorial monitoring" },
    availability: "available",
    implementation: "finalized",
  },
  {
    id: "godmode",
    categoryId: "pilotage",
    spaceId: "supervise",
    priority: 5,
    kind: "app-route",
    route: "/admin/godmode",
    label: { fr: "Mode administrateur", en: "God mode" },
    description: { fr: "Contrôle total du système", en: "Full system control" },
    availability: "available",
    implementation: "finalized",
  },
] as const satisfies readonly RubriqueDefinition[];
