import { buildGovernanceMonthlyReportPayload } from "./governance-monthly-report";
import { PROFIL_ROUTE } from "@/lib/accueil-pilotage-routes";

export const report = buildGovernanceMonthlyReportPayload({
    generatedAt: "2026-05-20T12:00:00.000Z",
    environmentalImpact: {
      status: "ok",
      model: {
        generatedAt: "2026-05-20T12:00:00.000Z",
        infrastructure: {
          monthlyKgCo2eProxy: 3.4,
          confidencePercent: 88,
          services: [
            {
              key: "supabase",
              label: "Supabase",
              monthlyKgCo2eProxy: 2.4,
              sharePercent: 61,
              confidencePercent: 84,
              uncertaintyPercent: 11,
              status: "ready",
            },
            {
              key: "vercel",
              label: "Vercel",
              monthlyKgCo2eProxy: 1.0,
              sharePercent: 29,
              confidencePercent: 82,
              uncertaintyPercent: 8,
              status: "ready",
            },
          ],
        },
      },
      signals: {
        generatedAt: "2026-05-20T12:00:00.000Z",
        signalBreakdown: {
          traffic: {
            pageViewEvents: 2,
            legacyPageViewEvents: 2,
            distinctRoutes: 2,
            topRoutes: [
              { path: "/community", count: 1 },
              { path: PROFIL_ROUTE, count: 1 },
            ],
          },
          community: {
            events: 1,
            rsvps: 2,
            notifications: 2,
            unreadNotifications: 1,
          },
          communication: {
            emailsSent: 2,
            pdfExports: 1,
          },
        },
      },
      snapshots: [
        {
          snapshotDate: "2026-05-20",
      model: {
        infrastructure: {
          services: [
            {
              key: "supabase",
              monthlyKgCo2eProxy: 2.4,
              sharePercent: 61,
              confidencePercent: 84,
              uncertaintyPercent: 11,
              status: "ready",
            },
            {
              key: "vercel",
              monthlyKgCo2eProxy: 1.0,
              sharePercent: 29,
              confidencePercent: 82,
              uncertaintyPercent: 8,
              status: "ready",
            },
          ],
        },
      },
        },
      ] as never,
      version: "environmental-impact-estimator-2026.05-v1",
    } as unknown as Parameters<typeof buildGovernanceMonthlyReportPayload>[0]["environmentalImpact"],
    storageUsage: {
      current: {
        quotaBytes: 1_000_000,
        quotaLabel: "1 MB",
        totalBytes: 120_000,
        totalLabel: "120 KB",
        remainingBytes: 880_000,
        remainingLabel: "880 KB",
        usagePercent: 12,
        objectCount: 4,
        bucketCount: 2,
        bucketBreakdown: [{ key: "a", label: "Bucket A", bytes: 70_000, count: 2, sharePercent: 58.3, averageBytes: 35_000 }],
        extensionBreakdown: [{ key: "pdf", label: "PDF", bytes: 80_000, count: 1, sharePercent: 66.6, averageBytes: 80_000 }],
        businessBreakdown: [],
        largestFiles: [],
        source: "default_free",
        warnings: [],
        generatedAt: "2026-05-20T12:00:00.000Z",
        snapshotMonth: "2026-05-01",
      },
      businessContributions: {
        previousSnapshotMonth: "2026-04-01",
        historyMonths: ["2026-05-01", "2026-04-01", "2026-03-01"],
        alerts: [],
        items: [
          {
            id: "socle_estimateur_impact",
            label: "Socle d’estimateur d’impact",
            description: "Exports, rapports et livrables du socle d’estimation.",
            currentBytes: 90_000,
            currentCount: 3,
            currentSharePercent: 75,
            currentAverageBytes: 30_000,
            previousBytes: 60_000,
            previousCount: 2,
            deltaBytes: 30_000,
            deltaPercent: 50,
            deltaCount: 1,
            cumulative3MonthBytes: 30_000,
            cumulative3MonthPercent: 50,
            accelerationBytes: 10_000,
            accelerationPercent: 50,
            history: [
              {
                snapshotMonth: "2026-05-01",
                monthLabel: "mai 2026",
                currentBytes: 90_000,
                currentCount: 3,
                sharePercent: 75,
                deltaBytes: 30_000,
                deltaCount: 1,
                deltaPercent: 50,
                cumulative3MonthBytes: 30_000,
                cumulative3MonthPercent: 50,
                accelerationBytes: 10_000,
                accelerationPercent: 50,
              },
            ],
            topFiles: [
              {
                bucketId: "reports",
                bucketLabel: "reports",
                name: "reports/governance-mensuel.pdf",
                extension: "pdf",
                bytes: 45_000,
                sizeLabel: "45 KB",
                createdAt: null,
                updatedAt: null,
              },
            ],
            mimeSubtypes: [
              { key: "application/pdf", label: "application/pdf", bytes: 45_000, count: 1, sharePercent: 50, averageBytes: 45_000 },
            ],
            alerts: [],
          },
          {
            id: "emails",
            label: "Emails",
            description: "Courriels, pièces de mail et artefacts d’envoi.",
            currentBytes: 12_000,
            currentCount: 2,
            currentSharePercent: 10,
            currentAverageBytes: 6_000,
            previousBytes: 10_000,
            previousCount: 2,
            deltaBytes: 2_000,
            deltaPercent: 20,
            deltaCount: 0,
            cumulative3MonthBytes: 2_000,
            cumulative3MonthPercent: 20,
            accelerationBytes: 0,
            accelerationPercent: 0,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
          {
            id: "messages",
            label: "Messages",
            description: "Échanges conversationnels et fils de discussion.",
            currentBytes: 8_000,
            currentCount: 4,
            currentSharePercent: 6.7,
            currentAverageBytes: 2_000,
            previousBytes: 4_000,
            previousCount: 2,
            deltaBytes: 4_000,
            deltaPercent: 100,
            deltaCount: 2,
            cumulative3MonthBytes: 4_000,
            cumulative3MonthPercent: 100,
            accelerationBytes: 2_000,
            accelerationPercent: 100,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
          {
            id: "pieces_jointes_document",
            label: "Pièces jointes document",
            description: "PDF, tableurs et documents partagés.",
            currentBytes: 6_000,
            currentCount: 1,
            currentSharePercent: 5,
            currentAverageBytes: 6_000,
            previousBytes: 6_000,
            previousCount: 1,
            deltaBytes: 0,
            deltaPercent: 0,
            deltaCount: 0,
            cumulative3MonthBytes: 0,
            cumulative3MonthPercent: 0,
            accelerationBytes: 0,
            accelerationPercent: 0,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
          {
            id: "pieces_jointes_photo",
            label: "Pièces jointes photo",
            description: "Images jointes aux conversations ou aux formulaires.",
            currentBytes: 4_000,
            currentCount: 1,
            currentSharePercent: 3.3,
            currentAverageBytes: 4_000,
            previousBytes: 3_500,
            previousCount: 1,
            deltaBytes: 500,
            deltaPercent: 14.3,
            deltaCount: 0,
            cumulative3MonthBytes: 500,
            cumulative3MonthPercent: 14.3,
            accelerationBytes: 250,
            accelerationPercent: 100,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
          {
            id: "actions_terrain",
            label: "Actions terrain",
            description: "Données et médias liés aux missions terrain.",
            currentBytes: 70_000,
            currentCount: 2,
            currentSharePercent: 58.3,
            currentAverageBytes: 35_000,
            previousBytes: 50_000,
            previousCount: 1,
            deltaBytes: 20_000,
            deltaPercent: 40,
            deltaCount: 1,
            cumulative3MonthBytes: 20_000,
            cumulative3MonthPercent: 40,
            accelerationBytes: 10_000,
            accelerationPercent: 100,
            history: [],
            topFiles: [
              {
                bucketId: "mission-assets",
                bucketLabel: "mission-assets",
                name: "mission-1/video.mp4",
                extension: "mp4",
                bytes: 40_000,
                sizeLabel: "40 KB",
                createdAt: null,
                updatedAt: null,
              },
              {
                bucketId: "mission-assets",
                bucketLabel: "mission-assets",
                name: "mission-1/photo.jpg",
                extension: "jpg",
                bytes: 30_000,
                sizeLabel: "30 KB",
                createdAt: null,
                updatedAt: null,
              },
            ],
            mimeSubtypes: [],
            alerts: [],
          },
          {
            id: "donnees_utilisateur",
            label: "Données utilisateur",
            description: "Profils, avatars et contenus attachés aux comptes.",
            currentBytes: 3_000,
            currentCount: 1,
            currentSharePercent: 2.5,
            currentAverageBytes: 3_000,
            previousBytes: 2_000,
            previousCount: 1,
            deltaBytes: 1_000,
            deltaPercent: 50,
            deltaCount: 0,
            cumulative3MonthBytes: 1_000,
            cumulative3MonthPercent: 50,
            accelerationBytes: 500,
            accelerationPercent: 100,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
          {
            id: "badges_gamification",
            label: "Badges gamification",
            description: "Récompenses, avatars de progression et badges.",
            currentBytes: 1_000,
            currentCount: 1,
            currentSharePercent: 0.8,
            currentAverageBytes: 1_000,
            previousBytes: 500,
            previousCount: 1,
            deltaBytes: 500,
            deltaPercent: 100,
            deltaCount: 0,
            cumulative3MonthBytes: 500,
            cumulative3MonthPercent: 100,
            accelerationBytes: 250,
            accelerationPercent: 100,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
        ],
      },
      history: [
        {
          snapshotMonth: "2026-05-01",
          monthLabel: "mai 2026",
          generatedAt: "2026-05-20T12:00:00.000Z",
          totalBytes: 120_000,
          usagePercent: 12,
          bucketBreakdown: [],
          extensionBreakdown: [],
          businessBreakdown: [],
        },
      ],
      comparison: {
        previousSnapshotMonth: null,
        deltaBytes: 20_000,
        deltaPercent: 20,
        bucketGrowth: [],
        extensionGrowth: [],
      },
      warnings: [],
      timestamp: "2026-05-20T12:00:00.000Z",
      snapshotMonth: "2026-05-01",
      snapshotPersisted: false,
      cron: {
        configured: true,
        statusLabel: "Configuré",
        schedule: "0 3 1 * *",
        scheduleLabel: "1er du mois à 03:00 UTC",
        timezone: "UTC",
        nextRunAt: "2026-06-01T03:00:00.000Z",
        nextRunLabel: "1 juin 2026 à 03:00 UTC",
      },
    } as unknown as Parameters<typeof buildGovernanceMonthlyReportPayload>[0]["storageUsage"],
  });
