import type { buildGovernanceMonthlyReportPayload } from "./governance-monthly-report";
import { PROFIL_ROUTE } from "@/lib/accueil-pilotage-routes";

const generatedAt = "2026-05-20T12:00:00.000Z";

export const highRiskEnvironmentalImpact = {
      status: "ok",
      model: {
        generatedAt,
        version: "environmental-impact-estimator-2026.05-v1",
        infrastructure: {
          monthlyKgCo2eProxy: 5.6,
          confidencePercent: 81,
          uncertaintyPercent: 10,
          services: [
            {
              key: "supabase",
              label: "Supabase",
              monthlyKgCo2eProxy: 2.4,
              sharePercent: 35,
              confidencePercent: 74,
              uncertaintyPercent: 18,
              status: "partial",
            },
            {
              key: "vercel",
              label: "Vercel",
              monthlyKgCo2eProxy: 3.2,
              sharePercent: 45,
              confidencePercent: 94,
              uncertaintyPercent: 4,
              status: "ready",
            },
          ],
        },
      },
      signals: {
        generatedAt,
        siteInput: { pageViews: 4 },
        userInput: {},
        infrastructureInput: {},
        signalBreakdown: {
          traffic: {
            pageViewEvents: 4,
            legacyPageViewEvents: 2,
            distinctRoutes: 2,
            topRoutes: [
              { path: "/community", count: 2 },
              { path: PROFIL_ROUTE, count: 1 },
            ],
          },
          community: {
            events: 1,
            rsvps: 2,
            notifications: 1,
            unreadNotifications: 1,
          },
          communication: {
            emailsSent: 1,
            pdfExports: 1,
          },
        },
      },
      snapshots: [
        {
          snapshotDate: "2026-05-20",
          model: {
            generatedAt,
            version: "environmental-impact-estimator-2026.05-v1",
            infrastructure: {
              services: [
                {
                  key: "supabase",
                  monthlyKgCo2eProxy: 2.4,
                  sharePercent: 35,
                  confidencePercent: 74,
                  uncertaintyPercent: 18,
                  status: "partial",
                },
                {
                  key: "vercel",
                  monthlyKgCo2eProxy: 3.2,
                  sharePercent: 45,
                  confidencePercent: 94,
                  uncertaintyPercent: 4,
                  status: "ready",
                },
              ],
            },
          },
        },
        {
          snapshotDate: "2026-04-20",
          model: {
            generatedAt: "2026-04-20T12:00:00.000Z",
            version: "environmental-impact-estimator-2026.04-v1",
            infrastructure: {
              services: [
                {
                  key: "supabase",
                  monthlyKgCo2eProxy: 1.0,
                  sharePercent: 24,
                  confidencePercent: 76,
                  uncertaintyPercent: 18,
                  status: "partial",
                },
                {
                  key: "vercel",
                  monthlyKgCo2eProxy: 0.4,
                  sharePercent: 18,
                  confidencePercent: 91,
                  uncertaintyPercent: 5,
                  status: "ready",
                },
              ],
            },
          },
        },
      ],
      version: "environmental-impact-estimator-2026.05-v1",
    } as Parameters<typeof buildGovernanceMonthlyReportPayload>[0]["environmentalImpact"];

export const highRiskStorageUsage = {
      current: {
        quotaBytes: 1_000_000,
        quotaLabel: "1 MB",
        totalBytes: 920_000,
        totalLabel: "920 KB",
        remainingBytes: 80_000,
        remainingLabel: "80 KB",
        usagePercent: 92,
        objectCount: 12,
        bucketCount: 3,
        bucketBreakdown: [
          { key: "reports", label: "reports", bytes: 500_000, count: 5, sharePercent: 54.3, averageBytes: 100_000 },
          { key: "uploads", label: "uploads", bytes: 280_000, count: 4, sharePercent: 30.4, averageBytes: 70_000 },
          { key: "avatars", label: "avatars", bytes: 140_000, count: 3, sharePercent: 15.2, averageBytes: 46_667 },
        ],
        extensionBreakdown: [
          { key: "pdf", label: "PDF", bytes: 500_000, count: 5, sharePercent: 54.3, averageBytes: 100_000 },
          { key: "jpg", label: "JPG", bytes: 280_000, count: 4, sharePercent: 30.4, averageBytes: 70_000 },
        ],
        businessBreakdown: [],
        largestFiles: [],
        source: "default_free",
        warnings: ["Le quota gratuit approche de la saturation."],
        generatedAt,
        snapshotMonth: "2026-05-01",
      },
      businessContributions: {
        previousSnapshotMonth: "2026-04-01",
        historyMonths: ["2026-05-01", "2026-04-01", "2026-03-01"],
        alerts: [
          {
            label: "socle_estimateur_impact",
            severity: "critical",
            title: "Exports du socle trop lourds",
            message: "Les exports du socle dépassent le seuil cible de gouvernance.",
            signal: "heavyExports",
          },
          {
            label: "pieces_jointes_photo",
            severity: "warning",
            title: "Les pièces jointes photo dominent",
            message: "Les pièces jointes photo pèsent désormais trop dans le quota.",
            signal: "photoDominance",
          },
        ],
        items: [
          {
            id: "socle_estimateur_impact",
            label: "Socle d’estimateur d’impact environnemental",
            description: "Exports, rapports et livrables du socle d’estimation.",
            currentBytes: 500_000,
            currentCount: 5,
            currentSharePercent: 54.3,
            currentAverageBytes: 100_000,
            previousBytes: 320_000,
            previousCount: 4,
            deltaBytes: 180_000,
            deltaPercent: 56.3,
            deltaCount: 1,
            cumulative3MonthBytes: 220_000,
            cumulative3MonthPercent: 43.1,
            accelerationBytes: 80_000,
            accelerationPercent: 57.1,
            history: [
              {
                snapshotMonth: "2026-05-01",
                monthLabel: "mai 2026",
                currentBytes: 500_000,
                currentCount: 5,
                sharePercent: 54.3,
                deltaBytes: 180_000,
                deltaCount: 1,
                deltaPercent: 56.3,
                cumulative3MonthBytes: 220_000,
                cumulative3MonthPercent: 43.1,
                accelerationBytes: 80_000,
                accelerationPercent: 57.1,
              },
            ],
            topFiles: [
              {
                bucketId: "reports",
                bucketLabel: "reports",
                name: "reports/governance-mensuel.pdf",
                extension: "pdf",
                bytes: 250_000,
                sizeLabel: "250 KB",
                createdAt: null,
                updatedAt: null,
              },
            ],
            mimeSubtypes: [
              { key: "application/pdf", label: "application/pdf", bytes: 250_000, count: 1, sharePercent: 50, averageBytes: 250_000 },
            ],
            alerts: [
              {
                severity: "critical",
                title: "Exports du socle trop lourds",
                message: "Le socle prend trop de place dans le quota.",
                signal: "heavyExports",
              },
            ],
          },
          {
            id: "pieces_jointes_photo",
            label: "Pièces jointes photo",
            description: "Photos terrain et pièces jointes visuelles.",
            currentBytes: 420_000,
            currentCount: 4,
            currentSharePercent: 45.7,
            currentAverageBytes: 105_000,
            previousBytes: 240_000,
            previousCount: 3,
            deltaBytes: 180_000,
            deltaPercent: 75,
            deltaCount: 1,
            cumulative3MonthBytes: 180_000,
            cumulative3MonthPercent: 75,
            accelerationBytes: 90_000,
            accelerationPercent: 100,
            history: [],
            topFiles: [],
            mimeSubtypes: [],
            alerts: [],
          },
        ],
      },
      history: [
        {
          snapshotMonth: "2026-05-01",
          monthLabel: "mai 2026",
          generatedAt,
          totalBytes: 920_000,
          usagePercent: 92,
          bucketBreakdown: [],
          extensionBreakdown: [],
          businessBreakdown: [],
        },
        {
          snapshotMonth: "2026-04-01",
          monthLabel: "avril 2026",
          generatedAt: "2026-04-20T12:00:00.000Z",
          totalBytes: 740_000,
          usagePercent: 74,
          bucketBreakdown: [],
          extensionBreakdown: [],
          businessBreakdown: [],
        },
        {
          snapshotMonth: "2026-03-01",
          monthLabel: "mars 2026",
          generatedAt: "2026-03-20T12:00:00.000Z",
          totalBytes: 610_000,
          usagePercent: 61,
          bucketBreakdown: [],
          extensionBreakdown: [],
          businessBreakdown: [],
        },
      ],
      comparison: {
        previousSnapshotMonth: "2026-04-01",
        deltaBytes: 180_000,
        deltaPercent: 24.3,
        bucketGrowth: [],
        extensionGrowth: [],
      },
      warnings: ["Le quota gratuit approche de la saturation."],
      timestamp: generatedAt,
      snapshotMonth: "2026-05-01",
      snapshotPersisted: false,
      cron: {
        configured: true,
        statusLabel: "Configuré",
        schedule: "0 3 1 * *",
        scheduleLabel: "1er du mois à 03:00 UTC",
        timezone: "UTC",
        nextRunAt: "2026-06-01T03:00:00.000Z",
        nextRunLabel: "1 juin 2026 à 03:00 UTC",
      },
    } as unknown as Parameters<typeof buildGovernanceMonthlyReportPayload>[0]["storageUsage"];
