-- 20260521000010_codex_usage_monitoring.sql

create table if not exists public.codex_usage_weekly_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_key text not null,
  week_start date not null,
  week_end date not null,
  generated_at timestamptz not null default now(),
  version text not null,
  source text not null check (source in ('manual', 'imported', 'reconstructed')),
  session_count integer not null default 0 check (session_count >= 0),
  conversation_count integer not null default 0 check (conversation_count >= 0),
  turn_count integer not null default 0 check (turn_count >= 0),
  tool_call_count integer not null default 0 check (tool_call_count >= 0),
  shell_command_count integer not null default 0 check (shell_command_count >= 0),
  file_touch_count integer not null default 0 check (file_touch_count >= 0),
  test_run_count integer not null default 0 check (test_run_count >= 0),
  changed_line_count integer not null default 0 check (changed_line_count >= 0),
  active_minutes numeric(12,2) not null default 0 check (active_minutes >= 0),
  estimated_kg_co2e_proxy numeric(14,6) not null default 0 check (estimated_kg_co2e_proxy >= 0),
  confidence_percent numeric(5,2) not null default 0,
  uncertainty_percent numeric(5,2) not null default 0,
  notes jsonb not null default '[]'::jsonb,
  meta jsonb not null default '{}'::jsonb
);

create unique index if not exists uq_codex_usage_weekly_snapshots_key_week
  on public.codex_usage_weekly_snapshots(snapshot_key, week_start);
create index if not exists idx_codex_usage_weekly_snapshots_generated_at_desc
  on public.codex_usage_weekly_snapshots(generated_at desc);
create index if not exists idx_codex_usage_weekly_snapshots_week_start_desc
  on public.codex_usage_weekly_snapshots(week_start desc);

alter table public.codex_usage_weekly_snapshots enable row level security;

drop policy if exists codex_usage_weekly_snapshots_service_only on public.codex_usage_weekly_snapshots;
create policy codex_usage_weekly_snapshots_service_only on public.codex_usage_weekly_snapshots
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
