-- 20260521000008_environmental_impact_history.sql

create table if not exists public.service_email_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  provider text not null default 'resend',
  actor_user_id text,
  recipient_count integer not null default 0 check (recipient_count >= 0),
  subject text not null,
  status text not null check (status in ('sent', 'mocked', 'missing_config', 'error')),
  message_id text,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists idx_service_email_events_created_at_desc
  on public.service_email_events(created_at desc);
create index if not exists idx_service_email_events_status
  on public.service_email_events(status);
create index if not exists idx_service_email_events_actor_user_id
  on public.service_email_events(actor_user_id);

create table if not exists public.environmental_impact_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_key text not null,
  snapshot_date date not null,
  generated_at timestamptz not null default now(),
  version text not null,
  launched_at timestamptz,
  account_created_at timestamptz,
  period_days integer not null check (period_days between 1 and 3650),
  total_kg_co2e_proxy numeric(14,6),
  monthly_kg_co2e_proxy numeric(14,6),
  annual_kg_co2e_proxy numeric(14,6),
  confidence_percent numeric(5,2) not null default 0,
  uncertainty_percent numeric(5,2) not null default 0,
  model jsonb not null default '{}'::jsonb,
  signals jsonb not null default '{}'::jsonb,
  notes jsonb not null default '[]'::jsonb
);

create unique index if not exists uq_environmental_impact_snapshots_key_date
  on public.environmental_impact_snapshots(snapshot_key, snapshot_date);
create index if not exists idx_environmental_impact_snapshots_generated_at_desc
  on public.environmental_impact_snapshots(generated_at desc);
create index if not exists idx_environmental_impact_snapshots_version
  on public.environmental_impact_snapshots(version);

alter table public.service_email_events enable row level security;
alter table public.environmental_impact_snapshots enable row level security;

drop policy if exists service_email_events_service_only on public.service_email_events;
create policy service_email_events_service_only on public.service_email_events
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists environmental_impact_snapshots_service_only on public.environmental_impact_snapshots;
create policy environmental_impact_snapshots_service_only on public.environmental_impact_snapshots
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
