-- 20260521000009_storage_usage_monitoring.sql

create table if not exists public.supabase_storage_usage_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_month date not null,
  generated_at timestamptz not null default now(),
  quota_bytes bigint not null check (quota_bytes >= 0),
  total_bytes bigint not null check (total_bytes >= 0),
  remaining_bytes bigint not null,
  usage_percent numeric(6,2) not null check (usage_percent >= 0),
  object_count integer not null default 0 check (object_count >= 0),
  bucket_breakdown jsonb not null default '[]'::jsonb,
  extension_breakdown jsonb not null default '[]'::jsonb,
  business_breakdown jsonb not null default '[]'::jsonb,
  largest_files jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb
);

create unique index if not exists uq_supabase_storage_usage_snapshots_month
  on public.supabase_storage_usage_snapshots(snapshot_month);

create index if not exists idx_supabase_storage_usage_snapshots_generated_at_desc
  on public.supabase_storage_usage_snapshots(generated_at desc);

alter table public.supabase_storage_usage_snapshots enable row level security;

drop policy if exists supabase_storage_usage_snapshots_service_only on public.supabase_storage_usage_snapshots;
create policy supabase_storage_usage_snapshots_service_only on public.supabase_storage_usage_snapshots
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
